package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AdrmstId generated by hbm2java
 */
@Embeddable
public class AdrmstId implements java.io.Serializable {

	private Serializable adrId;
	private Serializable clientId;
	private Serializable hostExtId;
	private Serializable adrnam;
	private Serializable adrtyp;
	private Serializable adrln1;
	private Serializable adrln2;
	private Serializable adrln3;
	private Serializable adrcty;
	private Serializable adrstc;
	private Serializable adrpsz;
	private Serializable ctryName;
	private Serializable rgncod;
	private Serializable phnnum;
	private Serializable faxnum;
	private Serializable attnName;
	private Serializable attnTel;
	private Serializable contName;
	private Serializable contTel;
	private Serializable contTitle;
	private Integer rsaflg;
	private Integer tempFlg;
	private Integer poBoxFlg;
	private Serializable lastName;
	private Serializable firstName;
	private Serializable honorific;
	private Serializable usrDsp;
	private Serializable adrDistrict;
	private Serializable webAdr;
	private Serializable emailAdr;
	private Serializable pagnum;
	private Serializable localeId;
	private Integer poolFlg;
	private Serializable poolRateServNam;
	private Serializable shipPhnnum;
	private Serializable shipFaxnum;
	private Serializable shipWebAdr;
	private Serializable shipEmailAdr;
	private Serializable shipContName;
	private Serializable shipContTitle;
	private Serializable shipContTel;
	private Serializable shipAttnName;
	private Serializable shipAttnPhnnum;
	private Serializable timZonCd;
	private Serializable rqstStateCod;
	private Serializable grpNam;
	private Serializable latitude;
	private Serializable longitude;
	private Serializable gln;
	private Serializable cstmsSiteTyp;
	private Serializable cstmsTxSite;

	public AdrmstId() {
	}

	public AdrmstId(Serializable adrId, Serializable adrnam) {
		this.adrId = adrId;
		this.adrnam = adrnam;
	}

	public AdrmstId(Serializable adrId, Serializable clientId, Serializable hostExtId, Serializable adrnam,
			Serializable adrtyp, Serializable adrln1, Serializable adrln2, Serializable adrln3, Serializable adrcty,
			Serializable adrstc, Serializable adrpsz, Serializable ctryName, Serializable rgncod, Serializable phnnum,
			Serializable faxnum, Serializable attnName, Serializable attnTel, Serializable contName,
			Serializable contTel, Serializable contTitle, Integer rsaflg, Integer tempFlg, Integer poBoxFlg,
			Serializable lastName, Serializable firstName, Serializable honorific, Serializable usrDsp,
			Serializable adrDistrict, Serializable webAdr, Serializable emailAdr, Serializable pagnum,
			Serializable localeId, Integer poolFlg, Serializable poolRateServNam, Serializable shipPhnnum,
			Serializable shipFaxnum, Serializable shipWebAdr, Serializable shipEmailAdr, Serializable shipContName,
			Serializable shipContTitle, Serializable shipContTel, Serializable shipAttnName,
			Serializable shipAttnPhnnum, Serializable timZonCd, Serializable rqstStateCod, Serializable grpNam,
			Serializable latitude, Serializable longitude, Serializable gln, Serializable cstmsSiteTyp,
			Serializable cstmsTxSite) {
		this.adrId = adrId;
		this.clientId = clientId;
		this.hostExtId = hostExtId;
		this.adrnam = adrnam;
		this.adrtyp = adrtyp;
		this.adrln1 = adrln1;
		this.adrln2 = adrln2;
		this.adrln3 = adrln3;
		this.adrcty = adrcty;
		this.adrstc = adrstc;
		this.adrpsz = adrpsz;
		this.ctryName = ctryName;
		this.rgncod = rgncod;
		this.phnnum = phnnum;
		this.faxnum = faxnum;
		this.attnName = attnName;
		this.attnTel = attnTel;
		this.contName = contName;
		this.contTel = contTel;
		this.contTitle = contTitle;
		this.rsaflg = rsaflg;
		this.tempFlg = tempFlg;
		this.poBoxFlg = poBoxFlg;
		this.lastName = lastName;
		this.firstName = firstName;
		this.honorific = honorific;
		this.usrDsp = usrDsp;
		this.adrDistrict = adrDistrict;
		this.webAdr = webAdr;
		this.emailAdr = emailAdr;
		this.pagnum = pagnum;
		this.localeId = localeId;
		this.poolFlg = poolFlg;
		this.poolRateServNam = poolRateServNam;
		this.shipPhnnum = shipPhnnum;
		this.shipFaxnum = shipFaxnum;
		this.shipWebAdr = shipWebAdr;
		this.shipEmailAdr = shipEmailAdr;
		this.shipContName = shipContName;
		this.shipContTitle = shipContTitle;
		this.shipContTel = shipContTel;
		this.shipAttnName = shipAttnName;
		this.shipAttnPhnnum = shipAttnPhnnum;
		this.timZonCd = timZonCd;
		this.rqstStateCod = rqstStateCod;
		this.grpNam = grpNam;
		this.latitude = latitude;
		this.longitude = longitude;
		this.gln = gln;
		this.cstmsSiteTyp = cstmsSiteTyp;
		this.cstmsTxSite = cstmsTxSite;
	}

	@Column(name = "adr_id", nullable = false)
	public Serializable getAdrId() {
		return this.adrId;
	}

	public void setAdrId(Serializable adrId) {
		this.adrId = adrId;
	}

	@Column(name = "client_id")
	public Serializable getClientId() {
		return this.clientId;
	}

	public void setClientId(Serializable clientId) {
		this.clientId = clientId;
	}

	@Column(name = "host_ext_id")
	public Serializable getHostExtId() {
		return this.hostExtId;
	}

	public void setHostExtId(Serializable hostExtId) {
		this.hostExtId = hostExtId;
	}

	@Column(name = "adrnam", nullable = false)
	public Serializable getAdrnam() {
		return this.adrnam;
	}

	public void setAdrnam(Serializable adrnam) {
		this.adrnam = adrnam;
	}

	@Column(name = "adrtyp")
	public Serializable getAdrtyp() {
		return this.adrtyp;
	}

	public void setAdrtyp(Serializable adrtyp) {
		this.adrtyp = adrtyp;
	}

	@Column(name = "adrln1")
	public Serializable getAdrln1() {
		return this.adrln1;
	}

	public void setAdrln1(Serializable adrln1) {
		this.adrln1 = adrln1;
	}

	@Column(name = "adrln2")
	public Serializable getAdrln2() {
		return this.adrln2;
	}

	public void setAdrln2(Serializable adrln2) {
		this.adrln2 = adrln2;
	}

	@Column(name = "adrln3")
	public Serializable getAdrln3() {
		return this.adrln3;
	}

	public void setAdrln3(Serializable adrln3) {
		this.adrln3 = adrln3;
	}

	@Column(name = "adrcty")
	public Serializable getAdrcty() {
		return this.adrcty;
	}

	public void setAdrcty(Serializable adrcty) {
		this.adrcty = adrcty;
	}

	@Column(name = "adrstc")
	public Serializable getAdrstc() {
		return this.adrstc;
	}

	public void setAdrstc(Serializable adrstc) {
		this.adrstc = adrstc;
	}

	@Column(name = "adrpsz")
	public Serializable getAdrpsz() {
		return this.adrpsz;
	}

	public void setAdrpsz(Serializable adrpsz) {
		this.adrpsz = adrpsz;
	}

	@Column(name = "ctry_name")
	public Serializable getCtryName() {
		return this.ctryName;
	}

	public void setCtryName(Serializable ctryName) {
		this.ctryName = ctryName;
	}

	@Column(name = "rgncod")
	public Serializable getRgncod() {
		return this.rgncod;
	}

	public void setRgncod(Serializable rgncod) {
		this.rgncod = rgncod;
	}

	@Column(name = "phnnum")
	public Serializable getPhnnum() {
		return this.phnnum;
	}

	public void setPhnnum(Serializable phnnum) {
		this.phnnum = phnnum;
	}

	@Column(name = "faxnum")
	public Serializable getFaxnum() {
		return this.faxnum;
	}

	public void setFaxnum(Serializable faxnum) {
		this.faxnum = faxnum;
	}

	@Column(name = "attn_name")
	public Serializable getAttnName() {
		return this.attnName;
	}

	public void setAttnName(Serializable attnName) {
		this.attnName = attnName;
	}

	@Column(name = "attn_tel")
	public Serializable getAttnTel() {
		return this.attnTel;
	}

	public void setAttnTel(Serializable attnTel) {
		this.attnTel = attnTel;
	}

	@Column(name = "cont_name")
	public Serializable getContName() {
		return this.contName;
	}

	public void setContName(Serializable contName) {
		this.contName = contName;
	}

	@Column(name = "cont_tel")
	public Serializable getContTel() {
		return this.contTel;
	}

	public void setContTel(Serializable contTel) {
		this.contTel = contTel;
	}

	@Column(name = "cont_title")
	public Serializable getContTitle() {
		return this.contTitle;
	}

	public void setContTitle(Serializable contTitle) {
		this.contTitle = contTitle;
	}

	@Column(name = "rsaflg")
	public Integer getRsaflg() {
		return this.rsaflg;
	}

	public void setRsaflg(Integer rsaflg) {
		this.rsaflg = rsaflg;
	}

	@Column(name = "temp_flg")
	public Integer getTempFlg() {
		return this.tempFlg;
	}

	public void setTempFlg(Integer tempFlg) {
		this.tempFlg = tempFlg;
	}

	@Column(name = "po_box_flg")
	public Integer getPoBoxFlg() {
		return this.poBoxFlg;
	}

	public void setPoBoxFlg(Integer poBoxFlg) {
		this.poBoxFlg = poBoxFlg;
	}

	@Column(name = "last_name")
	public Serializable getLastName() {
		return this.lastName;
	}

	public void setLastName(Serializable lastName) {
		this.lastName = lastName;
	}

	@Column(name = "first_name")
	public Serializable getFirstName() {
		return this.firstName;
	}

	public void setFirstName(Serializable firstName) {
		this.firstName = firstName;
	}

	@Column(name = "honorific")
	public Serializable getHonorific() {
		return this.honorific;
	}

	public void setHonorific(Serializable honorific) {
		this.honorific = honorific;
	}

	@Column(name = "usr_dsp")
	public Serializable getUsrDsp() {
		return this.usrDsp;
	}

	public void setUsrDsp(Serializable usrDsp) {
		this.usrDsp = usrDsp;
	}

	@Column(name = "adr_district")
	public Serializable getAdrDistrict() {
		return this.adrDistrict;
	}

	public void setAdrDistrict(Serializable adrDistrict) {
		this.adrDistrict = adrDistrict;
	}

	@Column(name = "web_adr")
	public Serializable getWebAdr() {
		return this.webAdr;
	}

	public void setWebAdr(Serializable webAdr) {
		this.webAdr = webAdr;
	}

	@Column(name = "email_adr")
	public Serializable getEmailAdr() {
		return this.emailAdr;
	}

	public void setEmailAdr(Serializable emailAdr) {
		this.emailAdr = emailAdr;
	}

	@Column(name = "pagnum")
	public Serializable getPagnum() {
		return this.pagnum;
	}

	public void setPagnum(Serializable pagnum) {
		this.pagnum = pagnum;
	}

	@Column(name = "locale_id")
	public Serializable getLocaleId() {
		return this.localeId;
	}

	public void setLocaleId(Serializable localeId) {
		this.localeId = localeId;
	}

	@Column(name = "pool_flg")
	public Integer getPoolFlg() {
		return this.poolFlg;
	}

	public void setPoolFlg(Integer poolFlg) {
		this.poolFlg = poolFlg;
	}

	@Column(name = "pool_rate_serv_nam")
	public Serializable getPoolRateServNam() {
		return this.poolRateServNam;
	}

	public void setPoolRateServNam(Serializable poolRateServNam) {
		this.poolRateServNam = poolRateServNam;
	}

	@Column(name = "ship_phnnum")
	public Serializable getShipPhnnum() {
		return this.shipPhnnum;
	}

	public void setShipPhnnum(Serializable shipPhnnum) {
		this.shipPhnnum = shipPhnnum;
	}

	@Column(name = "ship_faxnum")
	public Serializable getShipFaxnum() {
		return this.shipFaxnum;
	}

	public void setShipFaxnum(Serializable shipFaxnum) {
		this.shipFaxnum = shipFaxnum;
	}

	@Column(name = "ship_web_adr")
	public Serializable getShipWebAdr() {
		return this.shipWebAdr;
	}

	public void setShipWebAdr(Serializable shipWebAdr) {
		this.shipWebAdr = shipWebAdr;
	}

	@Column(name = "ship_email_adr")
	public Serializable getShipEmailAdr() {
		return this.shipEmailAdr;
	}

	public void setShipEmailAdr(Serializable shipEmailAdr) {
		this.shipEmailAdr = shipEmailAdr;
	}

	@Column(name = "ship_cont_name")
	public Serializable getShipContName() {
		return this.shipContName;
	}

	public void setShipContName(Serializable shipContName) {
		this.shipContName = shipContName;
	}

	@Column(name = "ship_cont_title")
	public Serializable getShipContTitle() {
		return this.shipContTitle;
	}

	public void setShipContTitle(Serializable shipContTitle) {
		this.shipContTitle = shipContTitle;
	}

	@Column(name = "ship_cont_tel")
	public Serializable getShipContTel() {
		return this.shipContTel;
	}

	public void setShipContTel(Serializable shipContTel) {
		this.shipContTel = shipContTel;
	}

	@Column(name = "ship_attn_name")
	public Serializable getShipAttnName() {
		return this.shipAttnName;
	}

	public void setShipAttnName(Serializable shipAttnName) {
		this.shipAttnName = shipAttnName;
	}

	@Column(name = "ship_attn_phnnum")
	public Serializable getShipAttnPhnnum() {
		return this.shipAttnPhnnum;
	}

	public void setShipAttnPhnnum(Serializable shipAttnPhnnum) {
		this.shipAttnPhnnum = shipAttnPhnnum;
	}

	@Column(name = "tim_zon_cd")
	public Serializable getTimZonCd() {
		return this.timZonCd;
	}

	public void setTimZonCd(Serializable timZonCd) {
		this.timZonCd = timZonCd;
	}

	@Column(name = "rqst_state_cod")
	public Serializable getRqstStateCod() {
		return this.rqstStateCod;
	}

	public void setRqstStateCod(Serializable rqstStateCod) {
		this.rqstStateCod = rqstStateCod;
	}

	@Column(name = "grp_nam")
	public Serializable getGrpNam() {
		return this.grpNam;
	}

	public void setGrpNam(Serializable grpNam) {
		this.grpNam = grpNam;
	}

	@Column(name = "latitude")
	public Serializable getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Serializable latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude")
	public Serializable getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Serializable longitude) {
		this.longitude = longitude;
	}

	@Column(name = "gln")
	public Serializable getGln() {
		return this.gln;
	}

	public void setGln(Serializable gln) {
		this.gln = gln;
	}

	@Column(name = "cstms_site_typ")
	public Serializable getCstmsSiteTyp() {
		return this.cstmsSiteTyp;
	}

	public void setCstmsSiteTyp(Serializable cstmsSiteTyp) {
		this.cstmsSiteTyp = cstmsSiteTyp;
	}

	@Column(name = "cstms_tx_site")
	public Serializable getCstmsTxSite() {
		return this.cstmsTxSite;
	}

	public void setCstmsTxSite(Serializable cstmsTxSite) {
		this.cstmsTxSite = cstmsTxSite;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdrmstId))
			return false;
		AdrmstId castOther = (AdrmstId) other;

		return ((this.getAdrId() == castOther.getAdrId()) || (this.getAdrId() != null && castOther.getAdrId() != null
				&& this.getAdrId().equals(castOther.getAdrId())))
				&& ((this.getClientId() == castOther.getClientId()) || (this.getClientId() != null
						&& castOther.getClientId() != null && this.getClientId().equals(castOther.getClientId())))
				&& ((this.getHostExtId() == castOther.getHostExtId()) || (this.getHostExtId() != null
						&& castOther.getHostExtId() != null && this.getHostExtId().equals(castOther.getHostExtId())))
				&& ((this.getAdrnam() == castOther.getAdrnam()) || (this.getAdrnam() != null
						&& castOther.getAdrnam() != null && this.getAdrnam().equals(castOther.getAdrnam())))
				&& ((this.getAdrtyp() == castOther.getAdrtyp()) || (this.getAdrtyp() != null
						&& castOther.getAdrtyp() != null && this.getAdrtyp().equals(castOther.getAdrtyp())))
				&& ((this.getAdrln1() == castOther.getAdrln1()) || (this.getAdrln1() != null
						&& castOther.getAdrln1() != null && this.getAdrln1().equals(castOther.getAdrln1())))
				&& ((this.getAdrln2() == castOther.getAdrln2()) || (this.getAdrln2() != null
						&& castOther.getAdrln2() != null && this.getAdrln2().equals(castOther.getAdrln2())))
				&& ((this.getAdrln3() == castOther.getAdrln3()) || (this.getAdrln3() != null
						&& castOther.getAdrln3() != null && this.getAdrln3().equals(castOther.getAdrln3())))
				&& ((this.getAdrcty() == castOther.getAdrcty()) || (this.getAdrcty() != null
						&& castOther.getAdrcty() != null && this.getAdrcty().equals(castOther.getAdrcty())))
				&& ((this.getAdrstc() == castOther.getAdrstc()) || (this.getAdrstc() != null
						&& castOther.getAdrstc() != null && this.getAdrstc().equals(castOther.getAdrstc())))
				&& ((this.getAdrpsz() == castOther.getAdrpsz()) || (this.getAdrpsz() != null
						&& castOther.getAdrpsz() != null && this.getAdrpsz().equals(castOther.getAdrpsz())))
				&& ((this.getCtryName() == castOther.getCtryName()) || (this.getCtryName() != null
						&& castOther.getCtryName() != null && this.getCtryName().equals(castOther.getCtryName())))
				&& ((this.getRgncod() == castOther.getRgncod()) || (this.getRgncod() != null
						&& castOther.getRgncod() != null && this.getRgncod().equals(castOther.getRgncod())))
				&& ((this.getPhnnum() == castOther.getPhnnum()) || (this.getPhnnum() != null
						&& castOther.getPhnnum() != null && this.getPhnnum().equals(castOther.getPhnnum())))
				&& ((this.getFaxnum() == castOther.getFaxnum()) || (this.getFaxnum() != null
						&& castOther.getFaxnum() != null && this.getFaxnum().equals(castOther.getFaxnum())))
				&& ((this.getAttnName() == castOther.getAttnName()) || (this.getAttnName() != null
						&& castOther.getAttnName() != null && this.getAttnName().equals(castOther.getAttnName())))
				&& ((this.getAttnTel() == castOther.getAttnTel()) || (this.getAttnTel() != null
						&& castOther.getAttnTel() != null && this.getAttnTel().equals(castOther.getAttnTel())))
				&& ((this.getContName() == castOther.getContName()) || (this.getContName() != null
						&& castOther.getContName() != null && this.getContName().equals(castOther.getContName())))
				&& ((this.getContTel() == castOther.getContTel()) || (this.getContTel() != null
						&& castOther.getContTel() != null && this.getContTel().equals(castOther.getContTel())))
				&& ((this.getContTitle() == castOther.getContTitle()) || (this.getContTitle() != null
						&& castOther.getContTitle() != null && this.getContTitle().equals(castOther.getContTitle())))
				&& ((this.getRsaflg() == castOther.getRsaflg()) || (this.getRsaflg() != null
						&& castOther.getRsaflg() != null && this.getRsaflg().equals(castOther.getRsaflg())))
				&& ((this.getTempFlg() == castOther.getTempFlg()) || (this.getTempFlg() != null
						&& castOther.getTempFlg() != null && this.getTempFlg().equals(castOther.getTempFlg())))
				&& ((this.getPoBoxFlg() == castOther.getPoBoxFlg()) || (this.getPoBoxFlg() != null
						&& castOther.getPoBoxFlg() != null && this.getPoBoxFlg().equals(castOther.getPoBoxFlg())))
				&& ((this.getLastName() == castOther.getLastName()) || (this.getLastName() != null
						&& castOther.getLastName() != null && this.getLastName().equals(castOther.getLastName())))
				&& ((this.getFirstName() == castOther.getFirstName()) || (this.getFirstName() != null
						&& castOther.getFirstName() != null && this.getFirstName().equals(castOther.getFirstName())))
				&& ((this.getHonorific() == castOther.getHonorific()) || (this.getHonorific() != null
						&& castOther.getHonorific() != null && this.getHonorific().equals(castOther.getHonorific())))
				&& ((this.getUsrDsp() == castOther.getUsrDsp()) || (this.getUsrDsp() != null
						&& castOther.getUsrDsp() != null && this.getUsrDsp().equals(castOther.getUsrDsp())))
				&& ((this.getAdrDistrict() == castOther.getAdrDistrict())
						|| (this.getAdrDistrict() != null && castOther.getAdrDistrict() != null
								&& this.getAdrDistrict().equals(castOther.getAdrDistrict())))
				&& ((this.getWebAdr() == castOther.getWebAdr()) || (this.getWebAdr() != null
						&& castOther.getWebAdr() != null && this.getWebAdr().equals(castOther.getWebAdr())))
				&& ((this.getEmailAdr() == castOther.getEmailAdr()) || (this.getEmailAdr() != null
						&& castOther.getEmailAdr() != null && this.getEmailAdr().equals(castOther.getEmailAdr())))
				&& ((this.getPagnum() == castOther.getPagnum()) || (this.getPagnum() != null
						&& castOther.getPagnum() != null && this.getPagnum().equals(castOther.getPagnum())))
				&& ((this.getLocaleId() == castOther.getLocaleId()) || (this.getLocaleId() != null
						&& castOther.getLocaleId() != null && this.getLocaleId().equals(castOther.getLocaleId())))
				&& ((this.getPoolFlg() == castOther.getPoolFlg()) || (this.getPoolFlg() != null
						&& castOther.getPoolFlg() != null && this.getPoolFlg().equals(castOther.getPoolFlg())))
				&& ((this.getPoolRateServNam() == castOther.getPoolRateServNam())
						|| (this.getPoolRateServNam() != null && castOther.getPoolRateServNam() != null
								&& this.getPoolRateServNam().equals(castOther.getPoolRateServNam())))
				&& ((this.getShipPhnnum() == castOther.getShipPhnnum()) || (this.getShipPhnnum() != null
						&& castOther.getShipPhnnum() != null && this.getShipPhnnum().equals(castOther.getShipPhnnum())))
				&& ((this.getShipFaxnum() == castOther.getShipFaxnum()) || (this.getShipFaxnum() != null
						&& castOther.getShipFaxnum() != null && this.getShipFaxnum().equals(castOther.getShipFaxnum())))
				&& ((this.getShipWebAdr() == castOther.getShipWebAdr()) || (this.getShipWebAdr() != null
						&& castOther.getShipWebAdr() != null && this.getShipWebAdr().equals(castOther.getShipWebAdr())))
				&& ((this.getShipEmailAdr() == castOther.getShipEmailAdr())
						|| (this.getShipEmailAdr() != null && castOther.getShipEmailAdr() != null
								&& this.getShipEmailAdr().equals(castOther.getShipEmailAdr())))
				&& ((this.getShipContName() == castOther.getShipContName())
						|| (this.getShipContName() != null && castOther.getShipContName() != null
								&& this.getShipContName().equals(castOther.getShipContName())))
				&& ((this.getShipContTitle() == castOther.getShipContTitle())
						|| (this.getShipContTitle() != null && castOther.getShipContTitle() != null
								&& this.getShipContTitle().equals(castOther.getShipContTitle())))
				&& ((this.getShipContTel() == castOther.getShipContTel())
						|| (this.getShipContTel() != null && castOther.getShipContTel() != null
								&& this.getShipContTel().equals(castOther.getShipContTel())))
				&& ((this.getShipAttnName() == castOther.getShipAttnName())
						|| (this.getShipAttnName() != null && castOther.getShipAttnName() != null
								&& this.getShipAttnName().equals(castOther.getShipAttnName())))
				&& ((this.getShipAttnPhnnum() == castOther.getShipAttnPhnnum())
						|| (this.getShipAttnPhnnum() != null && castOther.getShipAttnPhnnum() != null
								&& this.getShipAttnPhnnum().equals(castOther.getShipAttnPhnnum())))
				&& ((this.getTimZonCd() == castOther.getTimZonCd()) || (this.getTimZonCd() != null
						&& castOther.getTimZonCd() != null && this.getTimZonCd().equals(castOther.getTimZonCd())))
				&& ((this.getRqstStateCod() == castOther.getRqstStateCod())
						|| (this.getRqstStateCod() != null && castOther.getRqstStateCod() != null
								&& this.getRqstStateCod().equals(castOther.getRqstStateCod())))
				&& ((this.getGrpNam() == castOther.getGrpNam()) || (this.getGrpNam() != null
						&& castOther.getGrpNam() != null && this.getGrpNam().equals(castOther.getGrpNam())))
				&& ((this.getLatitude() == castOther.getLatitude()) || (this.getLatitude() != null
						&& castOther.getLatitude() != null && this.getLatitude().equals(castOther.getLatitude())))
				&& ((this.getLongitude() == castOther.getLongitude()) || (this.getLongitude() != null
						&& castOther.getLongitude() != null && this.getLongitude().equals(castOther.getLongitude())))
				&& ((this.getGln() == castOther.getGln()) || (this.getGln() != null && castOther.getGln() != null
						&& this.getGln().equals(castOther.getGln())))
				&& ((this.getCstmsSiteTyp() == castOther.getCstmsSiteTyp())
						|| (this.getCstmsSiteTyp() != null && castOther.getCstmsSiteTyp() != null
								&& this.getCstmsSiteTyp().equals(castOther.getCstmsSiteTyp())))
				&& ((this.getCstmsTxSite() == castOther.getCstmsTxSite())
						|| (this.getCstmsTxSite() != null && castOther.getCstmsTxSite() != null
								&& this.getCstmsTxSite().equals(castOther.getCstmsTxSite())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAdrId() == null ? 0 : this.getAdrId().hashCode());
		result = 37 * result + (getClientId() == null ? 0 : this.getClientId().hashCode());
		result = 37 * result + (getHostExtId() == null ? 0 : this.getHostExtId().hashCode());
		result = 37 * result + (getAdrnam() == null ? 0 : this.getAdrnam().hashCode());
		result = 37 * result + (getAdrtyp() == null ? 0 : this.getAdrtyp().hashCode());
		result = 37 * result + (getAdrln1() == null ? 0 : this.getAdrln1().hashCode());
		result = 37 * result + (getAdrln2() == null ? 0 : this.getAdrln2().hashCode());
		result = 37 * result + (getAdrln3() == null ? 0 : this.getAdrln3().hashCode());
		result = 37 * result + (getAdrcty() == null ? 0 : this.getAdrcty().hashCode());
		result = 37 * result + (getAdrstc() == null ? 0 : this.getAdrstc().hashCode());
		result = 37 * result + (getAdrpsz() == null ? 0 : this.getAdrpsz().hashCode());
		result = 37 * result + (getCtryName() == null ? 0 : this.getCtryName().hashCode());
		result = 37 * result + (getRgncod() == null ? 0 : this.getRgncod().hashCode());
		result = 37 * result + (getPhnnum() == null ? 0 : this.getPhnnum().hashCode());
		result = 37 * result + (getFaxnum() == null ? 0 : this.getFaxnum().hashCode());
		result = 37 * result + (getAttnName() == null ? 0 : this.getAttnName().hashCode());
		result = 37 * result + (getAttnTel() == null ? 0 : this.getAttnTel().hashCode());
		result = 37 * result + (getContName() == null ? 0 : this.getContName().hashCode());
		result = 37 * result + (getContTel() == null ? 0 : this.getContTel().hashCode());
		result = 37 * result + (getContTitle() == null ? 0 : this.getContTitle().hashCode());
		result = 37 * result + (getRsaflg() == null ? 0 : this.getRsaflg().hashCode());
		result = 37 * result + (getTempFlg() == null ? 0 : this.getTempFlg().hashCode());
		result = 37 * result + (getPoBoxFlg() == null ? 0 : this.getPoBoxFlg().hashCode());
		result = 37 * result + (getLastName() == null ? 0 : this.getLastName().hashCode());
		result = 37 * result + (getFirstName() == null ? 0 : this.getFirstName().hashCode());
		result = 37 * result + (getHonorific() == null ? 0 : this.getHonorific().hashCode());
		result = 37 * result + (getUsrDsp() == null ? 0 : this.getUsrDsp().hashCode());
		result = 37 * result + (getAdrDistrict() == null ? 0 : this.getAdrDistrict().hashCode());
		result = 37 * result + (getWebAdr() == null ? 0 : this.getWebAdr().hashCode());
		result = 37 * result + (getEmailAdr() == null ? 0 : this.getEmailAdr().hashCode());
		result = 37 * result + (getPagnum() == null ? 0 : this.getPagnum().hashCode());
		result = 37 * result + (getLocaleId() == null ? 0 : this.getLocaleId().hashCode());
		result = 37 * result + (getPoolFlg() == null ? 0 : this.getPoolFlg().hashCode());
		result = 37 * result + (getPoolRateServNam() == null ? 0 : this.getPoolRateServNam().hashCode());
		result = 37 * result + (getShipPhnnum() == null ? 0 : this.getShipPhnnum().hashCode());
		result = 37 * result + (getShipFaxnum() == null ? 0 : this.getShipFaxnum().hashCode());
		result = 37 * result + (getShipWebAdr() == null ? 0 : this.getShipWebAdr().hashCode());
		result = 37 * result + (getShipEmailAdr() == null ? 0 : this.getShipEmailAdr().hashCode());
		result = 37 * result + (getShipContName() == null ? 0 : this.getShipContName().hashCode());
		result = 37 * result + (getShipContTitle() == null ? 0 : this.getShipContTitle().hashCode());
		result = 37 * result + (getShipContTel() == null ? 0 : this.getShipContTel().hashCode());
		result = 37 * result + (getShipAttnName() == null ? 0 : this.getShipAttnName().hashCode());
		result = 37 * result + (getShipAttnPhnnum() == null ? 0 : this.getShipAttnPhnnum().hashCode());
		result = 37 * result + (getTimZonCd() == null ? 0 : this.getTimZonCd().hashCode());
		result = 37 * result + (getRqstStateCod() == null ? 0 : this.getRqstStateCod().hashCode());
		result = 37 * result + (getGrpNam() == null ? 0 : this.getGrpNam().hashCode());
		result = 37 * result + (getLatitude() == null ? 0 : this.getLatitude().hashCode());
		result = 37 * result + (getLongitude() == null ? 0 : this.getLongitude().hashCode());
		result = 37 * result + (getGln() == null ? 0 : this.getGln().hashCode());
		result = 37 * result + (getCstmsSiteTyp() == null ? 0 : this.getCstmsSiteTyp().hashCode());
		result = 37 * result + (getCstmsTxSite() == null ? 0 : this.getCstmsTxSite().hashCode());
		return result;
	}

}
