package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Adrmst generated by hbm2java
 */
@Entity
@Table(name = "adrmst", schema = "dbo", catalog = "Tactic")
public class Adrmst implements java.io.Serializable {

	private AdrmstId id;

	public Adrmst() {
	}

	public Adrmst(AdrmstId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "adrId", column = @Column(name = "adr_id", nullable = false) ),
			@AttributeOverride(name = "clientId", column = @Column(name = "client_id") ),
			@AttributeOverride(name = "hostExtId", column = @Column(name = "host_ext_id") ),
			@AttributeOverride(name = "adrnam", column = @Column(name = "adrnam", nullable = false) ),
			@AttributeOverride(name = "adrtyp", column = @Column(name = "adrtyp") ),
			@AttributeOverride(name = "adrln1", column = @Column(name = "adrln1") ),
			@AttributeOverride(name = "adrln2", column = @Column(name = "adrln2") ),
			@AttributeOverride(name = "adrln3", column = @Column(name = "adrln3") ),
			@AttributeOverride(name = "adrcty", column = @Column(name = "adrcty") ),
			@AttributeOverride(name = "adrstc", column = @Column(name = "adrstc") ),
			@AttributeOverride(name = "adrpsz", column = @Column(name = "adrpsz") ),
			@AttributeOverride(name = "ctryName", column = @Column(name = "ctry_name") ),
			@AttributeOverride(name = "rgncod", column = @Column(name = "rgncod") ),
			@AttributeOverride(name = "phnnum", column = @Column(name = "phnnum") ),
			@AttributeOverride(name = "faxnum", column = @Column(name = "faxnum") ),
			@AttributeOverride(name = "attnName", column = @Column(name = "attn_name") ),
			@AttributeOverride(name = "attnTel", column = @Column(name = "attn_tel") ),
			@AttributeOverride(name = "contName", column = @Column(name = "cont_name") ),
			@AttributeOverride(name = "contTel", column = @Column(name = "cont_tel") ),
			@AttributeOverride(name = "contTitle", column = @Column(name = "cont_title") ),
			@AttributeOverride(name = "rsaflg", column = @Column(name = "rsaflg") ),
			@AttributeOverride(name = "tempFlg", column = @Column(name = "temp_flg") ),
			@AttributeOverride(name = "poBoxFlg", column = @Column(name = "po_box_flg") ),
			@AttributeOverride(name = "lastName", column = @Column(name = "last_name") ),
			@AttributeOverride(name = "firstName", column = @Column(name = "first_name") ),
			@AttributeOverride(name = "honorific", column = @Column(name = "honorific") ),
			@AttributeOverride(name = "usrDsp", column = @Column(name = "usr_dsp") ),
			@AttributeOverride(name = "adrDistrict", column = @Column(name = "adr_district") ),
			@AttributeOverride(name = "webAdr", column = @Column(name = "web_adr") ),
			@AttributeOverride(name = "emailAdr", column = @Column(name = "email_adr") ),
			@AttributeOverride(name = "pagnum", column = @Column(name = "pagnum") ),
			@AttributeOverride(name = "localeId", column = @Column(name = "locale_id") ),
			@AttributeOverride(name = "poolFlg", column = @Column(name = "pool_flg") ),
			@AttributeOverride(name = "poolRateServNam", column = @Column(name = "pool_rate_serv_nam") ),
			@AttributeOverride(name = "shipPhnnum", column = @Column(name = "ship_phnnum") ),
			@AttributeOverride(name = "shipFaxnum", column = @Column(name = "ship_faxnum") ),
			@AttributeOverride(name = "shipWebAdr", column = @Column(name = "ship_web_adr") ),
			@AttributeOverride(name = "shipEmailAdr", column = @Column(name = "ship_email_adr") ),
			@AttributeOverride(name = "shipContName", column = @Column(name = "ship_cont_name") ),
			@AttributeOverride(name = "shipContTitle", column = @Column(name = "ship_cont_title") ),
			@AttributeOverride(name = "shipContTel", column = @Column(name = "ship_cont_tel") ),
			@AttributeOverride(name = "shipAttnName", column = @Column(name = "ship_attn_name") ),
			@AttributeOverride(name = "shipAttnPhnnum", column = @Column(name = "ship_attn_phnnum") ),
			@AttributeOverride(name = "timZonCd", column = @Column(name = "tim_zon_cd") ),
			@AttributeOverride(name = "rqstStateCod", column = @Column(name = "rqst_state_cod") ),
			@AttributeOverride(name = "grpNam", column = @Column(name = "grp_nam") ),
			@AttributeOverride(name = "latitude", column = @Column(name = "latitude") ),
			@AttributeOverride(name = "longitude", column = @Column(name = "longitude") ),
			@AttributeOverride(name = "gln", column = @Column(name = "gln") ),
			@AttributeOverride(name = "cstmsSiteTyp", column = @Column(name = "cstms_site_typ") ),
			@AttributeOverride(name = "cstmsTxSite", column = @Column(name = "cstms_tx_site") ) })
	public AdrmstId getId() {
		return this.id;
	}

	public void setId(AdrmstId id) {
		this.id = id;
	}

}
