package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DestinatariosSucursales generated by hbm2java
 */
@Entity
@Table(name = "Destinatarios_Sucursales", schema = "crm", catalog = "Tactic")
public class DestinatariosSucursales implements java.io.Serializable {

	private Integer id;
	private Destinatarios destinatarios;
	private String codigo;
	private String nombre;
	private Integer idCiudad;
	private Boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;
	private Set<PuntosEntrega> puntosEntregas = new HashSet<PuntosEntrega>(0);

	public DestinatariosSucursales() {
	}

	public DestinatariosSucursales(Integer id, Destinatarios destinatarios, String codigo, String nombre,
			Boolean activo, Date fechaActualizacion, String usuarioActualizacion) {
		this.id = id;
		this.destinatarios = destinatarios;
		this.codigo = codigo;
		this.nombre = nombre;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public DestinatariosSucursales(Integer id, Destinatarios destinatarios, String codigo, String nombre,
			Integer idCiudad, Boolean activo, Date fechaActualizacion, String usuarioActualizacion,
			Set<PuntosEntrega> puntosEntregas) {
		this.id = id;
		this.destinatarios = destinatarios;
		this.codigo = codigo;
		this.nombre = nombre;
		this.idCiudad = idCiudad;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.puntosEntregas = puntosEntregas;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Destinatario", nullable = false)
	public Destinatarios getDestinatarios() {
		return this.destinatarios;
	}

	public void setDestinatarios(Destinatarios destinatarios) {
		this.destinatarios = destinatarios;
	}

	@Column(name = "Codigo", nullable = false, length = 20)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "Nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Id_Ciudad")
	public Integer getIdCiudad() {
		return this.idCiudad;
	}

	public void setIdCiudad(Integer idCiudad) {
		this.idCiudad = idCiudad;
	}

	@Column(name = "Activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destinatariosSucursales")
	public Set<PuntosEntrega> getPuntosEntregas() {
		return this.puntosEntregas;
	}

	public void setPuntosEntregas(Set<PuntosEntrega> puntosEntregas) {
		this.puntosEntregas = puntosEntregas;
	}

}
