package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MenusSugerencia generated by hbm2java
 */
@Entity
@Table(name = "Menus_Sugerencia", schema = "ui", catalog = "Tactic")
public class MenusSugerencia implements java.io.Serializable {

	private Integer id;
	private MenusSugerencia menusSugerencia;
	private String codigo;
	private String nombre;
	private String descripcion;
	private String icono;
	private String comando;
	private String pagina;
	private Integer ordinal;
	private Boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;
	private Set<MenusSugerencia> menusSugerencias = new HashSet<MenusSugerencia>(0);

	public MenusSugerencia() {
	}

	public MenusSugerencia(Integer id, String codigo, String nombre, String descripcion, String icono, String comando,
			String pagina, Integer ordinal, Boolean activo, Date fechaActualizacion, String usuarioActualizacion) {
		this.id = id;
		this.codigo = codigo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.icono = icono;
		this.comando = comando;
		this.pagina = pagina;
		this.ordinal = ordinal;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public MenusSugerencia(Integer id, MenusSugerencia menusSugerencia, String codigo, String nombre,
			String descripcion, String icono, String comando, String pagina, Integer ordinal, Boolean activo,
			Date fechaActualizacion, String usuarioActualizacion, Set<MenusSugerencia> menusSugerencias) {
		this.id = id;
		this.menusSugerencia = menusSugerencia;
		this.codigo = codigo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.icono = icono;
		this.comando = comando;
		this.pagina = pagina;
		this.ordinal = ordinal;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.menusSugerencias = menusSugerencias;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Menu_Padre")
	public MenusSugerencia getMenusSugerencia() {
		return this.menusSugerencia;
	}

	public void setMenusSugerencia(MenusSugerencia menusSugerencia) {
		this.menusSugerencia = menusSugerencia;
	}

	@Column(name = "Codigo", nullable = false, length = 20)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "Nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Descripcion", nullable = false, length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "Icono", nullable = false, length = 50)
	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

	@Column(name = "Comando", nullable = false, length = 200)
	public String getComando() {
		return this.comando;
	}

	public void setComando(String comando) {
		this.comando = comando;
	}

	@Column(name = "Pagina", nullable = false, length = 200)
	public String getPagina() {
		return this.pagina;
	}

	public void setPagina(String pagina) {
		this.pagina = pagina;
	}

	@Column(name = "Ordinal", nullable = false)
	public Integer getOrdinal() {
		return this.ordinal;
	}

	public void setOrdinal(Integer ordinal) {
		this.ordinal = ordinal;
	}

	@Column(name = "Activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menusSugerencia")
	public Set<MenusSugerencia> getMenusSugerencias() {
		return this.menusSugerencias;
	}

	public void setMenusSugerencias(Set<MenusSugerencia> menusSugerencias) {
		this.menusSugerencias = menusSugerencias;
	}

}
