package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * OperadoresCentrosDistribucion generated by hbm2java
 */
@Entity
@Table(name = "Operadores_Centros_Distribucion", schema = "wms", catalog = "Tactic", uniqueConstraints = @UniqueConstraint(columnNames = "Codigo") )
public class OperadoresCentrosDistribucion implements java.io.Serializable {

	private Integer id;
	private Terceros terceros;
	private String codigo;
	private Boolean proveedor;
	private Boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;
	private Set<CentrosDistribucion> centrosDistribucions = new HashSet<CentrosDistribucion>(0);

	public OperadoresCentrosDistribucion() {
	}

	public OperadoresCentrosDistribucion(Terceros terceros, String codigo, Boolean proveedor, Boolean activo,
			Date fechaActualizacion, String usuarioActualizacion) {
		this.terceros = terceros;
		this.codigo = codigo;
		this.proveedor = proveedor;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public OperadoresCentrosDistribucion(Terceros terceros, String codigo, Boolean proveedor, Boolean activo,
			Date fechaActualizacion, String usuarioActualizacion, Set<CentrosDistribucion> centrosDistribucions) {
		this.terceros = terceros;
		this.codigo = codigo;
		this.proveedor = proveedor;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.centrosDistribucions = centrosDistribucions;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "terceros") )
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Terceros getTerceros() {
		return this.terceros;
	}

	public void setTerceros(Terceros terceros) {
		this.terceros = terceros;
	}

	@Column(name = "Codigo", unique = true, nullable = false, length = 20)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "Proveedor", nullable = false)
	public Boolean getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Boolean proveedor) {
		this.proveedor = proveedor;
	}

	@Column(name = "Activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operadoresCentrosDistribucion")
	public Set<CentrosDistribucion> getCentrosDistribucions() {
		return this.centrosDistribucions;
	}

	public void setCentrosDistribucions(Set<CentrosDistribucion> centrosDistribucions) {
		this.centrosDistribucions = centrosDistribucions;
	}

}
