package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Paises generated by hbm2java
 */
@Entity
@Table(name = "Paises", schema = "geo", catalog = "Tactic", uniqueConstraints = {
		@UniqueConstraint(columnNames = "Codigo"), @UniqueConstraint(columnNames = "Nombre") })
public class Paises implements java.io.Serializable {

	private Integer id;
	private String codigo;
	private String nombre;
	private BigDecimal longitud;
	private BigDecimal latitud;
	private Integer ordinal;
	private Boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;
	private Set<Departamentos> departamentoses = new HashSet<Departamentos>(0);

	public Paises() {
	}

	public Paises(Integer id, String codigo, String nombre, BigDecimal longitud, BigDecimal latitud, Integer ordinal,
			Boolean activo, Date fechaActualizacion, String usuarioActualizacion) {
		this.id = id;
		this.codigo = codigo;
		this.nombre = nombre;
		this.longitud = longitud;
		this.latitud = latitud;
		this.ordinal = ordinal;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public Paises(Integer id, String codigo, String nombre, BigDecimal longitud, BigDecimal latitud, Integer ordinal,
			Boolean activo, Date fechaActualizacion, String usuarioActualizacion, Set<Departamentos> departamentoses) {
		this.id = id;
		this.codigo = codigo;
		this.nombre = nombre;
		this.longitud = longitud;
		this.latitud = latitud;
		this.ordinal = ordinal;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.departamentoses = departamentoses;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Codigo", unique = true, nullable = false, length = 3)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "Nombre", unique = true, nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Longitud", nullable = false, precision = 18, scale = 15)
	public BigDecimal getLongitud() {
		return this.longitud;
	}

	public void setLongitud(BigDecimal longitud) {
		this.longitud = longitud;
	}

	@Column(name = "Latitud", nullable = false, precision = 18, scale = 15)
	public BigDecimal getLatitud() {
		return this.latitud;
	}

	public void setLatitud(BigDecimal latitud) {
		this.latitud = latitud;
	}

	@Column(name = "Ordinal", nullable = false)
	public Integer getOrdinal() {
		return this.ordinal;
	}

	public void setOrdinal(Integer ordinal) {
		this.ordinal = ordinal;
	}

	@Column(name = "Activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paises")
	public Set<Departamentos> getDepartamentoses() {
		return this.departamentoses;
	}

	public void setDepartamentoses(Set<Departamentos> departamentoses) {
		this.departamentoses = departamentoses;
	}

}
