package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PedidosDestinosVentanasEntrega generated by hbm2java
 */
@Entity
@Table(name = "Pedidos_Destinos_Ventanas_Entrega", schema = "crm", catalog = "Tactic")
public class PedidosDestinosVentanasEntrega implements java.io.Serializable {

	private Integer id;
	private PedidosDestinos pedidosDestinos;
	private TiposHorarioPuntoEntrega tiposHorarioPuntoEntrega;
	private Date fechaInicio;
	private Date fechaFin;
	private Date horaInicio;
	private Date horaFin;
	private Date fechaActualizacion;
	private String usuarioActualizacion;

	public PedidosDestinosVentanasEntrega() {
	}

	public PedidosDestinosVentanasEntrega(PedidosDestinos pedidosDestinos,
			TiposHorarioPuntoEntrega tiposHorarioPuntoEntrega, Date fechaInicio, Date fechaFin, Date horaInicio,
			Date horaFin, Date fechaActualizacion, String usuarioActualizacion) {
		this.pedidosDestinos = pedidosDestinos;
		this.tiposHorarioPuntoEntrega = tiposHorarioPuntoEntrega;
		this.fechaInicio = fechaInicio;
		this.fechaFin = fechaFin;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "pedidosDestinos") )
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public PedidosDestinos getPedidosDestinos() {
		return this.pedidosDestinos;
	}

	public void setPedidosDestinos(PedidosDestinos pedidosDestinos) {
		this.pedidosDestinos = pedidosDestinos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Tipo_Horario_Punto_Entrega", nullable = false)
	public TiposHorarioPuntoEntrega getTiposHorarioPuntoEntrega() {
		return this.tiposHorarioPuntoEntrega;
	}

	public void setTiposHorarioPuntoEntrega(TiposHorarioPuntoEntrega tiposHorarioPuntoEntrega) {
		this.tiposHorarioPuntoEntrega = tiposHorarioPuntoEntrega;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Inicio", nullable = false, length = 19)
	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Fin", nullable = false, length = 19)
	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "Hora_Inicio", nullable = false, length = 8)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "Hora_Fin", nullable = false, length = 8)
	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

}
