package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PedidosProductosLotesParticularidades generated by hbm2java
 */
@Entity
@Table(name = "Pedidos_Productos_Lotes_Particularidades", schema = "wms", catalog = "Tactic")
public class PedidosProductosLotesParticularidades implements java.io.Serializable {

	private Integer id;
	private Integer idPedidoProductoLote;
	private Integer idParticularidad;
	private Date fechaActualizacion;
	private String usuarioActualizacion;

	public PedidosProductosLotesParticularidades() {
	}

	public PedidosProductosLotesParticularidades(Integer id, Integer idPedidoProductoLote, Integer idParticularidad,
			Date fechaActualizacion, String usuarioActualizacion) {
		this.id = id;
		this.idPedidoProductoLote = idPedidoProductoLote;
		this.idParticularidad = idParticularidad;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Id_Pedido_Producto_Lote", nullable = false)
	public Integer getIdPedidoProductoLote() {
		return this.idPedidoProductoLote;
	}

	public void setIdPedidoProductoLote(Integer idPedidoProductoLote) {
		this.idPedidoProductoLote = idPedidoProductoLote;
	}

	@Column(name = "Id_Particularidad", nullable = false)
	public Integer getIdParticularidad() {
		return this.idParticularidad;
	}

	public void setIdParticularidad(Integer idParticularidad) {
		this.idParticularidad = idParticularidad;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

}
