package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PedidosDestinosDireccionesOriginales generated by hbm2java
 */
@Entity
@Table(name = "Pedidos_Destinos_Direcciones_Originales", schema = "crm", catalog = "Tactic")
public class PedidosDestinosDireccionesOriginales implements java.io.Serializable {

	private Integer id;
	private PedidosDestinos pedidosDestinos;
	private Barrios barrios;
	private Ciudades ciudades;
	private Localidades localidades;
	private String codigoPuntoEntrega;
	private String nombrePuntoEntrega;
	private String nombreDepartamento;
	private String nombreCiudad;
	private String codigoCiudad;
	private Boolean urbana;
	private String direccionOriginal;
	private String direccionEstandarizada;
	private Integer idAbreviaturaVialViaPrincipal;
	private String viaPrincipal;
	private String viaGeneradora;
	private String numeroPlaca;
	private String indicaciones;
	private String codigoZona;
	private Integer idZona;
	private String nombreLocalidad;
	private String nombreBarrio;
	private String codigoPostal;
	private String nombreContacto;
	private String cargoContacto;
	private String telefonoFijo;
	private String telefonoMovil;
	private String telefonoFax;
	private String email;
	private Date fechaActualizacion;
	private String usuarioActualizacion;

	public PedidosDestinosDireccionesOriginales() {
	}

	public PedidosDestinosDireccionesOriginales(PedidosDestinos pedidosDestinos, String codigoPuntoEntrega,
			String nombrePuntoEntrega, String nombreDepartamento, String nombreCiudad, String codigoCiudad,
			Boolean urbana, String direccionOriginal, String direccionEstandarizada, String viaPrincipal,
			String viaGeneradora, String numeroPlaca, String indicaciones, String codigoZona, String nombreLocalidad,
			String nombreBarrio, String codigoPostal, String nombreContacto, String cargoContacto, String telefonoFijo,
			String telefonoMovil, String telefonoFax, String email, Date fechaActualizacion,
			String usuarioActualizacion) {
		this.pedidosDestinos = pedidosDestinos;
		this.codigoPuntoEntrega = codigoPuntoEntrega;
		this.nombrePuntoEntrega = nombrePuntoEntrega;
		this.nombreDepartamento = nombreDepartamento;
		this.nombreCiudad = nombreCiudad;
		this.codigoCiudad = codigoCiudad;
		this.urbana = urbana;
		this.direccionOriginal = direccionOriginal;
		this.direccionEstandarizada = direccionEstandarizada;
		this.viaPrincipal = viaPrincipal;
		this.viaGeneradora = viaGeneradora;
		this.numeroPlaca = numeroPlaca;
		this.indicaciones = indicaciones;
		this.codigoZona = codigoZona;
		this.nombreLocalidad = nombreLocalidad;
		this.nombreBarrio = nombreBarrio;
		this.codigoPostal = codigoPostal;
		this.nombreContacto = nombreContacto;
		this.cargoContacto = cargoContacto;
		this.telefonoFijo = telefonoFijo;
		this.telefonoMovil = telefonoMovil;
		this.telefonoFax = telefonoFax;
		this.email = email;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public PedidosDestinosDireccionesOriginales(PedidosDestinos pedidosDestinos, Barrios barrios, Ciudades ciudades,
			Localidades localidades, String codigoPuntoEntrega, String nombrePuntoEntrega, String nombreDepartamento,
			String nombreCiudad, String codigoCiudad, Boolean urbana, String direccionOriginal,
			String direccionEstandarizada, Integer idAbreviaturaVialViaPrincipal, String viaPrincipal,
			String viaGeneradora, String numeroPlaca, String indicaciones, String codigoZona, Integer idZona,
			String nombreLocalidad, String nombreBarrio, String codigoPostal, String nombreContacto,
			String cargoContacto, String telefonoFijo, String telefonoMovil, String telefonoFax, String email,
			Date fechaActualizacion, String usuarioActualizacion) {
		this.pedidosDestinos = pedidosDestinos;
		this.barrios = barrios;
		this.ciudades = ciudades;
		this.localidades = localidades;
		this.codigoPuntoEntrega = codigoPuntoEntrega;
		this.nombrePuntoEntrega = nombrePuntoEntrega;
		this.nombreDepartamento = nombreDepartamento;
		this.nombreCiudad = nombreCiudad;
		this.codigoCiudad = codigoCiudad;
		this.urbana = urbana;
		this.direccionOriginal = direccionOriginal;
		this.direccionEstandarizada = direccionEstandarizada;
		this.idAbreviaturaVialViaPrincipal = idAbreviaturaVialViaPrincipal;
		this.viaPrincipal = viaPrincipal;
		this.viaGeneradora = viaGeneradora;
		this.numeroPlaca = numeroPlaca;
		this.indicaciones = indicaciones;
		this.codigoZona = codigoZona;
		this.idZona = idZona;
		this.nombreLocalidad = nombreLocalidad;
		this.nombreBarrio = nombreBarrio;
		this.codigoPostal = codigoPostal;
		this.nombreContacto = nombreContacto;
		this.cargoContacto = cargoContacto;
		this.telefonoFijo = telefonoFijo;
		this.telefonoMovil = telefonoMovil;
		this.telefonoFax = telefonoFax;
		this.email = email;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "pedidosDestinos") )
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public PedidosDestinos getPedidosDestinos() {
		return this.pedidosDestinos;
	}

	public void setPedidosDestinos(PedidosDestinos pedidosDestinos) {
		this.pedidosDestinos = pedidosDestinos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Barrio")
	public Barrios getBarrios() {
		return this.barrios;
	}

	public void setBarrios(Barrios barrios) {
		this.barrios = barrios;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Ciudad")
	public Ciudades getCiudades() {
		return this.ciudades;
	}

	public void setCiudades(Ciudades ciudades) {
		this.ciudades = ciudades;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Localidad")
	public Localidades getLocalidades() {
		return this.localidades;
	}

	public void setLocalidades(Localidades localidades) {
		this.localidades = localidades;
	}

	@Column(name = "Codigo_Punto_Entrega", nullable = false, length = 20)
	public String getCodigoPuntoEntrega() {
		return this.codigoPuntoEntrega;
	}

	public void setCodigoPuntoEntrega(String codigoPuntoEntrega) {
		this.codigoPuntoEntrega = codigoPuntoEntrega;
	}

	@Column(name = "Nombre_Punto_Entrega", nullable = false, length = 50)
	public String getNombrePuntoEntrega() {
		return this.nombrePuntoEntrega;
	}

	public void setNombrePuntoEntrega(String nombrePuntoEntrega) {
		this.nombrePuntoEntrega = nombrePuntoEntrega;
	}

	@Column(name = "Nombre_Departamento", nullable = false, length = 50)
	public String getNombreDepartamento() {
		return this.nombreDepartamento;
	}

	public void setNombreDepartamento(String nombreDepartamento) {
		this.nombreDepartamento = nombreDepartamento;
	}

	@Column(name = "Nombre_Ciudad", nullable = false, length = 50)
	public String getNombreCiudad() {
		return this.nombreCiudad;
	}

	public void setNombreCiudad(String nombreCiudad) {
		this.nombreCiudad = nombreCiudad;
	}

	@Column(name = "Codigo_Ciudad", nullable = false, length = 10)
	public String getCodigoCiudad() {
		return this.codigoCiudad;
	}

	public void setCodigoCiudad(String codigoCiudad) {
		this.codigoCiudad = codigoCiudad;
	}

	@Column(name = "Urbana", nullable = false)
	public Boolean getUrbana() {
		return this.urbana;
	}

	public void setUrbana(Boolean urbana) {
		this.urbana = urbana;
	}

	@Column(name = "Direccion_Original", nullable = false, length = 150)
	public String getDireccionOriginal() {
		return this.direccionOriginal;
	}

	public void setDireccionOriginal(String direccionOriginal) {
		this.direccionOriginal = direccionOriginal;
	}

	@Column(name = "Direccion_Estandarizada", nullable = false, length = 150)
	public String getDireccionEstandarizada() {
		return this.direccionEstandarizada;
	}

	public void setDireccionEstandarizada(String direccionEstandarizada) {
		this.direccionEstandarizada = direccionEstandarizada;
	}

	@Column(name = "Id_Abreviatura_Vial_Via_Principal")
	public Integer getIdAbreviaturaVialViaPrincipal() {
		return this.idAbreviaturaVialViaPrincipal;
	}

	public void setIdAbreviaturaVialViaPrincipal(Integer idAbreviaturaVialViaPrincipal) {
		this.idAbreviaturaVialViaPrincipal = idAbreviaturaVialViaPrincipal;
	}

	@Column(name = "Via_Principal", nullable = false, length = 50)
	public String getViaPrincipal() {
		return this.viaPrincipal;
	}

	public void setViaPrincipal(String viaPrincipal) {
		this.viaPrincipal = viaPrincipal;
	}

	@Column(name = "Via_Generadora", nullable = false, length = 50)
	public String getViaGeneradora() {
		return this.viaGeneradora;
	}

	public void setViaGeneradora(String viaGeneradora) {
		this.viaGeneradora = viaGeneradora;
	}

	@Column(name = "Numero_Placa", nullable = false, length = 50)
	public String getNumeroPlaca() {
		return this.numeroPlaca;
	}

	public void setNumeroPlaca(String numeroPlaca) {
		this.numeroPlaca = numeroPlaca;
	}

	@Column(name = "Indicaciones", nullable = false, length = 100)
	public String getIndicaciones() {
		return this.indicaciones;
	}

	public void setIndicaciones(String indicaciones) {
		this.indicaciones = indicaciones;
	}

	@Column(name = "Codigo_Zona", nullable = false, length = 20)
	public String getCodigoZona() {
		return this.codigoZona;
	}

	public void setCodigoZona(String codigoZona) {
		this.codigoZona = codigoZona;
	}

	@Column(name = "Id_Zona")
	public Integer getIdZona() {
		return this.idZona;
	}

	public void setIdZona(Integer idZona) {
		this.idZona = idZona;
	}

	@Column(name = "Nombre_Localidad", nullable = false, length = 50)
	public String getNombreLocalidad() {
		return this.nombreLocalidad;
	}

	public void setNombreLocalidad(String nombreLocalidad) {
		this.nombreLocalidad = nombreLocalidad;
	}

	@Column(name = "Nombre_Barrio", nullable = false, length = 50)
	public String getNombreBarrio() {
		return this.nombreBarrio;
	}

	public void setNombreBarrio(String nombreBarrio) {
		this.nombreBarrio = nombreBarrio;
	}

	@Column(name = "Codigo_Postal", nullable = false, length = 10)
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@Column(name = "Nombre_Contacto", nullable = false, length = 100)
	public String getNombreContacto() {
		return this.nombreContacto;
	}

	public void setNombreContacto(String nombreContacto) {
		this.nombreContacto = nombreContacto;
	}

	@Column(name = "Cargo_Contacto", nullable = false, length = 50)
	public String getCargoContacto() {
		return this.cargoContacto;
	}

	public void setCargoContacto(String cargoContacto) {
		this.cargoContacto = cargoContacto;
	}

	@Column(name = "Telefono_Fijo", nullable = false, length = 20)
	public String getTelefonoFijo() {
		return this.telefonoFijo;
	}

	public void setTelefonoFijo(String telefonoFijo) {
		this.telefonoFijo = telefonoFijo;
	}

	@Column(name = "Telefono_Movil", nullable = false, length = 20)
	public String getTelefonoMovil() {
		return this.telefonoMovil;
	}

	public void setTelefonoMovil(String telefonoMovil) {
		this.telefonoMovil = telefonoMovil;
	}

	@Column(name = "Telefono_Fax", nullable = false, length = 20)
	public String getTelefonoFax() {
		return this.telefonoFax;
	}

	public void setTelefonoFax(String telefonoFax) {
		this.telefonoFax = telefonoFax;
	}

	@Column(name = "Email", nullable = false, length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

}
