package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name = "Productos", schema = "wms", catalog = "Tactic")
public class Productos implements java.io.Serializable,EntityId {

    private Integer id;
    private Clientes clientes;
    private FamiliasProductos familiasProductos;
    private String codigo;
    private String huella;
    private String nombreCorto;
    private String nombreLargo;
    private Boolean activo;
    private Date fechaActualizacion;
    private String usuarioActualizacion;
    private Set<ProductosUoM> productosUoMs = new HashSet<>(0);
    private Set<PedidosProductos> pedidosProductoses = new HashSet<>(0);
    private Set<CentrosDistribucionProductos> centrosDistribucionProductoses = new HashSet<>(
            0);
    private Set<PuntosEntregaProductos> puntosEntregaProductoses = new HashSet<>(0);

    public Productos() {
    }

    public Productos(Integer id, Clientes clientes, FamiliasProductos familiasProductos, String codigo, String huella,
            String nombreCorto, String nombreLargo, Boolean activo, Date fechaActualizacion,
            String usuarioActualizacion) {
        this.id = id;
        this.clientes = clientes;
        this.familiasProductos = familiasProductos;
        this.codigo = codigo;
        this.huella = huella;
        this.nombreCorto = nombreCorto;
        this.nombreLargo = nombreLargo;
        this.activo = activo;
        this.fechaActualizacion = fechaActualizacion;
        this.usuarioActualizacion = usuarioActualizacion;
    }

    public Productos(Integer id, Clientes clientes, FamiliasProductos familiasProductos, String codigo, String huella,
            String nombreCorto, String nombreLargo, Boolean activo, Date fechaActualizacion,
            String usuarioActualizacion, Set<ProductosUoM> productosUoMs, Set<PedidosProductos> pedidosProductoses,
            Set<CentrosDistribucionProductos> centrosDistribucionProductoses,
            Set<PuntosEntregaProductos> puntosEntregaProductoses) {
        this.id = id;
        this.clientes = clientes;
        this.familiasProductos = familiasProductos;
        this.codigo = codigo;
        this.huella = huella;
        this.nombreCorto = nombreCorto;
        this.nombreLargo = nombreLargo;
        this.activo = activo;
        this.fechaActualizacion = fechaActualizacion;
        this.usuarioActualizacion = usuarioActualizacion;
        this.productosUoMs = productosUoMs;
        this.pedidosProductoses = pedidosProductoses;
        this.centrosDistribucionProductoses = centrosDistribucionProductoses;
        this.puntosEntregaProductoses = puntosEntregaProductoses;
    }

    @Id
    @Column(name = "Id", unique = true, nullable = false)
    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Id_Cliente", nullable = false)
    public Clientes getClientes() {
        return this.clientes;
    }

    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Id_Familia_Producto", nullable = false)
    public FamiliasProductos getFamiliasProductos() {
        return this.familiasProductos;
    }

    public void setFamiliasProductos(FamiliasProductos familiasProductos) {
        this.familiasProductos = familiasProductos;
    }

    @Column(name = "Codigo", nullable = false, length = 50)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Column(name = "Huella", nullable = false, length = 30)
    public String getHuella() {
        return this.huella;
    }

    public void setHuella(String huella) {
        this.huella = huella;
    }

    @Column(name = "Nombre_Corto", nullable = false, length = 20)
    public String getNombreCorto() {
        return this.nombreCorto;
    }

    public void setNombreCorto(String nombreCorto) {
        this.nombreCorto = nombreCorto;
    }

    @Column(name = "Nombre_Largo", nullable = false, length = 250)
    public String getNombreLargo() {
        return this.nombreLargo;
    }

    public void setNombreLargo(String nombreLargo) {
        this.nombreLargo = nombreLargo;
    }

    @Column(name = "Activo", nullable = false)
    public Boolean getActivo() {
        return this.activo;
    }

    public void setActivo(Boolean activo) {
        this.activo = activo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    @Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
    public String getUsuarioActualizacion() {
        return this.usuarioActualizacion;
    }

    public void setUsuarioActualizacion(String usuarioActualizacion) {
        this.usuarioActualizacion = usuarioActualizacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "productos")
    public Set<ProductosUoM> getProductosUoMs() {
        return this.productosUoMs;
    }

    public void setProductosUoMs(Set<ProductosUoM> productosUoMs) {
        this.productosUoMs = productosUoMs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "productos")
    public Set<PedidosProductos> getPedidosProductoses() {
        return this.pedidosProductoses;
    }

    public void setPedidosProductoses(Set<PedidosProductos> pedidosProductoses) {
        this.pedidosProductoses = pedidosProductoses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "productos")
    public Set<CentrosDistribucionProductos> getCentrosDistribucionProductoses() {
        return this.centrosDistribucionProductoses;
    }

    public void setCentrosDistribucionProductoses(Set<CentrosDistribucionProductos> centrosDistribucionProductoses) {
        this.centrosDistribucionProductoses = centrosDistribucionProductoses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "productos")
    public Set<PuntosEntregaProductos> getPuntosEntregaProductoses() {
        return this.puntosEntregaProductoses;
    }

    public void setPuntosEntregaProductoses(Set<PuntosEntregaProductos> puntosEntregaProductoses) {
        this.puntosEntregaProductoses = puntosEntregaProductoses;
    }

}
