package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PrtdscId generated by hbm2java
 */
@Embeddable
public class PrtdscId implements java.io.Serializable {

	private Serializable colnam;
	private Serializable colval;
	private Serializable localeId;
	private Serializable lngdsc;
	private Serializable shortDsc;

	public PrtdscId() {
	}

	public PrtdscId(Serializable colnam, Serializable colval, Serializable localeId, Serializable lngdsc) {
		this.colnam = colnam;
		this.colval = colval;
		this.localeId = localeId;
		this.lngdsc = lngdsc;
	}

	public PrtdscId(Serializable colnam, Serializable colval, Serializable localeId, Serializable lngdsc,
			Serializable shortDsc) {
		this.colnam = colnam;
		this.colval = colval;
		this.localeId = localeId;
		this.lngdsc = lngdsc;
		this.shortDsc = shortDsc;
	}

	@Column(name = "colnam", nullable = false)
	public Serializable getColnam() {
		return this.colnam;
	}

	public void setColnam(Serializable colnam) {
		this.colnam = colnam;
	}

	@Column(name = "colval", nullable = false)
	public Serializable getColval() {
		return this.colval;
	}

	public void setColval(Serializable colval) {
		this.colval = colval;
	}

	@Column(name = "locale_id", nullable = false)
	public Serializable getLocaleId() {
		return this.localeId;
	}

	public void setLocaleId(Serializable localeId) {
		this.localeId = localeId;
	}

	@Column(name = "lngdsc", nullable = false)
	public Serializable getLngdsc() {
		return this.lngdsc;
	}

	public void setLngdsc(Serializable lngdsc) {
		this.lngdsc = lngdsc;
	}

	@Column(name = "short_dsc")
	public Serializable getShortDsc() {
		return this.shortDsc;
	}

	public void setShortDsc(Serializable shortDsc) {
		this.shortDsc = shortDsc;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PrtdscId))
			return false;
		PrtdscId castOther = (PrtdscId) other;

		return ((this.getColnam() == castOther.getColnam()) || (this.getColnam() != null
				&& castOther.getColnam() != null && this.getColnam().equals(castOther.getColnam())))
				&& ((this.getColval() == castOther.getColval()) || (this.getColval() != null
						&& castOther.getColval() != null && this.getColval().equals(castOther.getColval())))
				&& ((this.getLocaleId() == castOther.getLocaleId()) || (this.getLocaleId() != null
						&& castOther.getLocaleId() != null && this.getLocaleId().equals(castOther.getLocaleId())))
				&& ((this.getLngdsc() == castOther.getLngdsc()) || (this.getLngdsc() != null
						&& castOther.getLngdsc() != null && this.getLngdsc().equals(castOther.getLngdsc())))
				&& ((this.getShortDsc() == castOther.getShortDsc()) || (this.getShortDsc() != null
						&& castOther.getShortDsc() != null && this.getShortDsc().equals(castOther.getShortDsc())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getColnam() == null ? 0 : this.getColnam().hashCode());
		result = 37 * result + (getColval() == null ? 0 : this.getColval().hashCode());
		result = 37 * result + (getLocaleId() == null ? 0 : this.getLocaleId().hashCode());
		result = 37 * result + (getLngdsc() == null ? 0 : this.getLngdsc().hashCode());
		result = 37 * result + (getShortDsc() == null ? 0 : this.getShortDsc().hashCode());
		return result;
	}

}
