package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Prtdsc generated by hbm2java
 */
@Entity
@Table(name = "prtdsc", schema = "dbo", catalog = "Tactic")
public class Prtdsc implements java.io.Serializable {

	private PrtdscId id;

	public Prtdsc() {
	}

	public Prtdsc(PrtdscId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "colnam", column = @Column(name = "colnam", nullable = false) ),
			@AttributeOverride(name = "colval", column = @Column(name = "colval", nullable = false) ),
			@AttributeOverride(name = "localeId", column = @Column(name = "locale_id", nullable = false) ),
			@AttributeOverride(name = "lngdsc", column = @Column(name = "lngdsc", nullable = false) ),
			@AttributeOverride(name = "shortDsc", column = @Column(name = "short_dsc") ) })
	public PrtdscId getId() {
		return this.id;
	}

	public void setId(PrtdscId id) {
		this.id = id;
	}

}
