package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PrtftpDtl generated by hbm2java
 */
@Entity
@Table(name = "prtftp_dtl", schema = "dbo", catalog = "Tactic")
public class PrtftpDtl implements java.io.Serializable {

	private PrtftpDtlId id;

	public PrtftpDtl() {
	}

	public PrtftpDtl(PrtftpDtlId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "prtnum", column = @Column(name = "prtnum", nullable = false) ),
			@AttributeOverride(name = "ftpcod", column = @Column(name = "ftpcod", nullable = false) ),
			@AttributeOverride(name = "prtClientId", column = @Column(name = "prt_client_id", nullable = false) ),
			@AttributeOverride(name = "whId", column = @Column(name = "wh_id", nullable = false) ),
			@AttributeOverride(name = "uomcod", column = @Column(name = "uomcod", nullable = false) ),
			@AttributeOverride(name = "uomlvl", column = @Column(name = "uomlvl", nullable = false) ),
			@AttributeOverride(name = "len", column = @Column(name = "len", nullable = false, scale = 4) ),
			@AttributeOverride(name = "wid", column = @Column(name = "wid", nullable = false, scale = 4) ),
			@AttributeOverride(name = "hgt", column = @Column(name = "hgt", nullable = false, scale = 4) ),
			@AttributeOverride(name = "grswgt", column = @Column(name = "grswgt", nullable = false, precision = 23, scale = 8) ),
			@AttributeOverride(name = "netwgt", column = @Column(name = "netwgt", nullable = false, precision = 23, scale = 8) ),
			@AttributeOverride(name = "palFlg", column = @Column(name = "pal_flg", nullable = false) ),
			@AttributeOverride(name = "casFlg", column = @Column(name = "cas_flg", nullable = false) ),
			@AttributeOverride(name = "pakFlg", column = @Column(name = "pak_flg", nullable = false) ),
			@AttributeOverride(name = "stkFlg", column = @Column(name = "stk_flg", nullable = false) ),
			@AttributeOverride(name = "rcvFlg", column = @Column(name = "rcv_flg", nullable = false) ),
			@AttributeOverride(name = "untqty", column = @Column(name = "untqty", nullable = false) ),
			@AttributeOverride(name = "ctnFlg", column = @Column(name = "ctn_flg", nullable = false) ),
			@AttributeOverride(name = "threshPct", column = @Column(name = "thresh_pct", nullable = false, scale = 4) ),
			@AttributeOverride(name = "ctnDstrFlg", column = @Column(name = "ctn_dstr_flg", nullable = false) ),
			@AttributeOverride(name = "bulkPckFlg", column = @Column(name = "bulk_pck_flg", nullable = false) ),
			@AttributeOverride(name = "insDt", column = @Column(name = "ins_dt", length = 23) ),
			@AttributeOverride(name = "lastUpdDt", column = @Column(name = "last_upd_dt", length = 23) ),
			@AttributeOverride(name = "insUserId", column = @Column(name = "ins_user_id") ),
			@AttributeOverride(name = "lastUpdUserId", column = @Column(name = "last_upd_user_id") ) })
	public PrtftpDtlId getId() {
		return this.id;
	}

	public void setId(PrtftpDtlId id) {
		this.id = id;
	}

}
