package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PrtfamGrp generated by hbm2java
 */
@Entity
@Table(name = "prtfam_grp", schema = "dbo", catalog = "Tactic")
public class PrtfamGrp implements java.io.Serializable {

	private PrtfamGrpId id;

	public PrtfamGrp() {
	}

	public PrtfamGrp(PrtfamGrpId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "prtfamgrp", column = @Column(name = "prtfamgrp", nullable = false) ),
			@AttributeOverride(name = "UVersion", column = @Column(name = "u_version") ),
			@AttributeOverride(name = "insDt", column = @Column(name = "ins_dt", length = 23) ),
			@AttributeOverride(name = "lastUpdDt", column = @Column(name = "last_upd_dt", length = 23) ),
			@AttributeOverride(name = "insUserId", column = @Column(name = "ins_user_id") ),
			@AttributeOverride(name = "lastUpdUserId", column = @Column(name = "last_upd_user_id") ) })
	public PrtfamGrpId getId() {
		return this.id;
	}

	public void setId(PrtfamGrpId id) {
		this.id = id;
	}

}
