package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PuntosEntregaHorarios generated by hbm2java
 */
@Entity
@Table(name = "Puntos_Entrega_Horarios", schema = "tms", catalog = "Tactic")
public class PuntosEntregaHorarios implements java.io.Serializable {

	private Integer id;
	private PuntosEntrega puntosEntrega;
	private TiposHorarioPuntoEntrega tiposHorarioPuntoEntrega;
	private Date horaInicio;
	private Date horaFin;
	private Boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;

	public PuntosEntregaHorarios() {
	}

	public PuntosEntregaHorarios(Integer id, PuntosEntrega puntosEntrega,
			TiposHorarioPuntoEntrega tiposHorarioPuntoEntrega, Date horaInicio, Date horaFin, Boolean activo,
			Date fechaActualizacion, String usuarioActualizacion) {
		this.id = id;
		this.puntosEntrega = puntosEntrega;
		this.tiposHorarioPuntoEntrega = tiposHorarioPuntoEntrega;
		this.horaInicio = horaInicio;
		this.horaFin = horaFin;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Punto_Entrega", nullable = false)
	public PuntosEntrega getPuntosEntrega() {
		return this.puntosEntrega;
	}

	public void setPuntosEntrega(PuntosEntrega puntosEntrega) {
		this.puntosEntrega = puntosEntrega;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Tipo_Horario_Punto_Entrega", nullable = false)
	public TiposHorarioPuntoEntrega getTiposHorarioPuntoEntrega() {
		return this.tiposHorarioPuntoEntrega;
	}

	public void setTiposHorarioPuntoEntrega(TiposHorarioPuntoEntrega tiposHorarioPuntoEntrega) {
		this.tiposHorarioPuntoEntrega = tiposHorarioPuntoEntrega;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "Hora_Inicio", nullable = false, length = 8)
	public Date getHoraInicio() {
		return this.horaInicio;
	}

	public void setHoraInicio(Date horaInicio) {
		this.horaInicio = horaInicio;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "Hora_Fin", nullable = false, length = 8)
	public Date getHoraFin() {
		return this.horaFin;
	}

	public void setHoraFin(Date horaFin) {
		this.horaFin = horaFin;
	}

	@Column(name = "Activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

}
