package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PuntosEntregaProductos generated by hbm2java
 */
@Entity
@Table(name = "Puntos_Entrega_Productos", schema = "tms", catalog = "Tactic", uniqueConstraints = @UniqueConstraint(columnNames = {
		"Id_Punto_Entrega", "Id_Producto" }) )
public class PuntosEntregaProductos implements java.io.Serializable {

	private Integer id;
	private PuntosEntrega puntosEntrega;
	private Productos productos;
	private Date fechaActualizacion;
	private String usuarioActualizacion;

	public PuntosEntregaProductos() {
	}

	public PuntosEntregaProductos(Integer id, PuntosEntrega puntosEntrega, Productos productos, Date fechaActualizacion,
			String usuarioActualizacion) {
		this.id = id;
		this.puntosEntrega = puntosEntrega;
		this.productos = productos;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Punto_Entrega", nullable = false)
	public PuntosEntrega getPuntosEntrega() {
		return this.puntosEntrega;
	}

	public void setPuntosEntrega(PuntosEntrega puntosEntrega) {
		this.puntosEntrega = puntosEntrega;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Producto", nullable = false)
	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

}
