package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * Solicitudes generated by hbm2java
 */
@Entity
@Table(name = "Solicitudes", schema = "id_georef", catalog = "Tactic")
public class Solicitudes implements java.io.Serializable, EntityId {

    private Integer id;
    private Date fechaSolicitud;
    private String codigoMunicipio;
    private String nombreMunicipio;
    private String direccion;
    private BigDecimal cx;
    private BigDecimal cy;
    private String estado;
    private String direccionEstandarizada;
    private String fuenteDireccion;
    private String direccionAlterna;
    private String nivelSocioEconomico;
    private String codigoBarrio;
    private String nombreBarrio;
    private String codigoLocalidad;
    private String nombreLocalidad;
    private String usuarioActualizacion;
    private Date fechaActualizacion;
    private String direccionSugeridaGeoReferenciacionManual;
    private String usuarioGeoReferenciacionManual;
    private Date fechaGeoReferenciacionManual;
    private EstadosSolicitud estadosSolicitudes;
    private TiposSolicitud tiposSolicitud;
    private Integer idTipoGeoReferenciacion;
    private String nombreCanal;
    private String nombreDestinatario;
    private String nombreDestino;

    public Solicitudes() {
    }

    public Solicitudes(Integer id, Date fechaSolicitud, String codigoMunicipio, String nombreMunicipio,
            String direccion) {
        this.id = id;
        this.fechaSolicitud = fechaSolicitud;
        this.codigoMunicipio = codigoMunicipio;
        this.nombreMunicipio = nombreMunicipio;
        this.direccion = direccion;
    }

    public Solicitudes(Integer id, Date fechaSolicitud, String codigoMunicipio, String nombreMunicipio,
            String direccion, BigDecimal cx, BigDecimal cy, String estado, String direccionEstandarizada,
            String fuenteDireccion, String direccionAlterna, String nivelSocioEconomico, String codigoBarrio,
            String nombreBarrio, String codigoLocalidad, String nombreLocalidad, Date fechaActualizacion) {
        this.id = id;
        this.fechaSolicitud = fechaSolicitud;
        this.codigoMunicipio = codigoMunicipio;
        this.nombreMunicipio = nombreMunicipio;
        this.direccion = direccion;
        this.cx = cx;
        this.cy = cy;
        this.estado = estado;
        this.direccionEstandarizada = direccionEstandarizada;
        this.fuenteDireccion = fuenteDireccion;
        this.direccionAlterna = direccionAlterna;
        this.nivelSocioEconomico = nivelSocioEconomico;
        this.codigoBarrio = codigoBarrio;
        this.nombreBarrio = nombreBarrio;
        this.codigoLocalidad = codigoLocalidad;
        this.nombreLocalidad = nombreLocalidad;
        this.fechaActualizacion = fechaActualizacion;
    }

    @Id
    @Column(name = "Id_Solicitud", nullable = false)
    @Override
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "Fecha_Solicitud", nullable = false, length = 19)
    @Temporal(javax.persistence.TemporalType.DATE)
    public Date getFechaSolicitud() {
        return this.fechaSolicitud;
    }

    public void setFechaSolicitud(Date fechaSolicitud) {
        this.fechaSolicitud = fechaSolicitud;
    }

    @Column(name = "Codigo_Municipio", nullable = false, length = 5)
    public String getCodigoMunicipio() {
        return this.codigoMunicipio;
    }

    public void setCodigoMunicipio(String codigoMunicipio) {
        this.codigoMunicipio = codigoMunicipio;
    }

    @Column(name = "Nombre_Municipio", nullable = false, length = 200)
    public String getNombreMunicipio() {
        return this.nombreMunicipio;
    }

    public void setNombreMunicipio(String nombreMunicipio) {
        this.nombreMunicipio = nombreMunicipio;
    }

    @Column(name = "Direccion", nullable = false, length = 150)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Column(name = "CX", precision = 18, scale = 15)
    public BigDecimal getCx() {
        return this.cx;
    }

    public void setCx(BigDecimal cx) {
        this.cx = cx;
    }

    @Column(name = "CY", precision = 18, scale = 15)
    public BigDecimal getCy() {
        return this.cy;
    }

    public void setCy(BigDecimal cy) {
        this.cy = cy;
    }

    @Column(name = "Estado", length = 2)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Column(name = "Direccion_Estandarizada", length = 150)
    public String getDireccionEstandarizada() {
        return this.direccionEstandarizada;
    }

    public void setDireccionEstandarizada(String direccionEstandarizada) {
        this.direccionEstandarizada = direccionEstandarizada;
    }

    @Column(name = "Fuente_Direccion", length = 150)
    public String getFuenteDireccion() {
        return this.fuenteDireccion;
    }

    public void setFuenteDireccion(String fuenteDireccion) {
        this.fuenteDireccion = fuenteDireccion;
    }

    @Column(name = "Direccion_Alterna", length = 150)
    public String getDireccionAlterna() {
        return this.direccionAlterna;
    }

    public void setDireccionAlterna(String direccionAlterna) {
        this.direccionAlterna = direccionAlterna;
    }

    @Column(name = "Nivel_Socio_Economico", length = 2)
    public String getNivelSocioEconomico() {
        return this.nivelSocioEconomico;
    }

    public void setNivelSocioEconomico(String nivelSocioEconomico) {
        this.nivelSocioEconomico = nivelSocioEconomico;
    }

    @Column(name = "Codigo_Barrio", length = 10)
    public String getCodigoBarrio() {
        return this.codigoBarrio;
    }

    public void setCodigoBarrio(String codigoBarrio) {
        this.codigoBarrio = codigoBarrio;
    }

    @Column(name = "Nombre_Barrio", length = 60)
    public String getNombreBarrio() {
        return this.nombreBarrio;
    }

    public void setNombreBarrio(String nombreBarrio) {
        this.nombreBarrio = nombreBarrio;
    }

    @Column(name = "Codigo_Localidad", length = 10)
    public String getCodigoLocalidad() {
        return this.codigoLocalidad;
    }

    public void setCodigoLocalidad(String codigoLocalidad) {
        this.codigoLocalidad = codigoLocalidad;
    }

    @Column(name = "Nombre_Localidad", length = 50)
    public String getNombreLocalidad() {
        return this.nombreLocalidad;
    }

    public void setNombreLocalidad(String nombreLocalidad) {
        this.nombreLocalidad = nombreLocalidad;
    }

    @Column(name = "usuario_actualizacion", length = 50)
    public String getUsuarioActualizacion() {
        return usuarioActualizacion;
    }

    public void setUsuarioActualizacion(String usuarioActualizacion) {
        this.usuarioActualizacion = usuarioActualizacion;
    }

    @Column(name = "Fecha_Actualizacion", length = 19)
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    @Column(name = "Direccion_Sugerida_GeoReferenciacion_Manual", length = 150)
    public String getDireccionSugeridaGeoReferenciacionManual() {
        return direccionSugeridaGeoReferenciacionManual;
    }

    public void setDireccionSugeridaGeoReferenciacionManual(String direccionSugeridaGeoReferenciacionManual) {
        this.direccionSugeridaGeoReferenciacionManual = direccionSugeridaGeoReferenciacionManual;
    }

    @Column(name = "Usuario_GeoReferenciacion_Manual", length = 50)
    public String getUsuarioGeoReferenciacionManual() {
        return usuarioGeoReferenciacionManual;
    }

    public void setUsuarioGeoReferenciacionManual(String usuarioGeoReferenciacionManual) {
        this.usuarioGeoReferenciacionManual = usuarioGeoReferenciacionManual;
    }

    @Column(name = "Fecha_GeoReferenciacion_Manual", length = 19)
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    public Date getFechaGeoReferenciacionManual() {
        return fechaGeoReferenciacionManual;
    }

    public void setFechaGeoReferenciacionManual(Date fechaGeoReferenciacionManual) {
        this.fechaGeoReferenciacionManual = fechaGeoReferenciacionManual;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "Id_Estado_Solicitud", nullable = false)
    public EstadosSolicitud getEstadosSolicitudes() {
        return estadosSolicitudes;
    }

    public void setEstadosSolicitudes(EstadosSolicitud estadosSolicitudes) {
        this.estadosSolicitudes = estadosSolicitudes;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "Id_Tipo_Solicitud", nullable = false)
    public TiposSolicitud getTiposSolicitud() {
        return tiposSolicitud;
    }

    public void setTiposSolicitud(TiposSolicitud tiposSolicitud) {
        this.tiposSolicitud = tiposSolicitud;
    }

    @Column(name = "Id_Tipo_GeoReferenciacion")
    public Integer getIdTipoGeoReferenciacion() {
        return idTipoGeoReferenciacion;
    }

    public void setIdTipoGeoReferenciacion(Integer idTipoGeoReferenciacion) {
        this.idTipoGeoReferenciacion = idTipoGeoReferenciacion;
    }

    @Column(name = "Nombre_Canal", length = 150)
    public String getNombreCanal() {
        return nombreCanal;
    }

    public void setNombreCanal(String nombreCanal) {
        this.nombreCanal = nombreCanal;
    }

    @Column(name = "Nombre_Destinatario", length = 150)
    public String getNombreDestinatario() {
        return nombreDestinatario;
    }

    public void setNombreDestinatario(String nombreDestinatario) {
        this.nombreDestinatario = nombreDestinatario;
    }

    @Column(name = "Nombre_Destino", length = 150)
    public String getNombreDestino() {
        return nombreDestino;
    }

    public void setNombreDestino(String nombreDestino) {
        this.nombreDestino = nombreDestino;
    }

}
