package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Terceros generated by hbm2java
 */
@Entity
@Table(name = "Terceros", schema = "dbo", catalog = "Tactic", uniqueConstraints = @UniqueConstraint(columnNames = {
    "Numero_Identificacion", "Id_Tipo_Identificacion", "Id_Tercero_Propietario"}))
public class Terceros implements java.io.Serializable {

    private Integer id;
    private Terceros terceros;
    private TiposIdentificacion tiposIdentificacion;
    private String numeroIdentificacion;
    private String digitoVerificacion;
    private String codigo;
    private String razonSocial;
    private String nombres;
    private String apellidos;
    private Boolean activo;
    private Date fechaActualizacion;
    private String usuarioActualizacion;
    private OperadoresCentrosDistribucion operadoresCentrosDistribucion;
    private Destinatarios destinatarios;
    private Set<Direcciones> direccioneses = new HashSet<Direcciones>(0);
    private Clientes clientes;
    private Set<Terceros> terceroses = new HashSet<Terceros>(0);

    public Terceros() {
    }

    public Terceros(Integer id, TiposIdentificacion tiposIdentificacion, String numeroIdentificacion,
            String digitoVerificacion, String codigo, String razonSocial, String nombres, String apellidos,
            Boolean activo, Date fechaActualizacion, String usuarioActualizacion) {
        this.id = id;
        this.tiposIdentificacion = tiposIdentificacion;
        this.numeroIdentificacion = numeroIdentificacion;
        this.digitoVerificacion = digitoVerificacion;
        this.codigo = codigo;
        this.razonSocial = razonSocial;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.activo = activo;
        this.fechaActualizacion = fechaActualizacion;
        this.usuarioActualizacion = usuarioActualizacion;
    }

    public Terceros(Integer id, Terceros terceros, TiposIdentificacion tiposIdentificacion, String numeroIdentificacion,
            String digitoVerificacion, String codigo, String razonSocial, String nombres, String apellidos,
            Boolean activo, Date fechaActualizacion, String usuarioActualizacion,
            OperadoresCentrosDistribucion operadoresCentrosDistribucion, Destinatarios destinatarios,
            Set<Direcciones> direccioneses, Clientes clientes, Set<Terceros> terceroses) {
        this.id = id;
        this.terceros = terceros;
        this.tiposIdentificacion = tiposIdentificacion;
        this.numeroIdentificacion = numeroIdentificacion;
        this.digitoVerificacion = digitoVerificacion;
        this.codigo = codigo;
        this.razonSocial = razonSocial;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.activo = activo;
        this.fechaActualizacion = fechaActualizacion;
        this.usuarioActualizacion = usuarioActualizacion;
        this.operadoresCentrosDistribucion = operadoresCentrosDistribucion;
        this.destinatarios = destinatarios;
        this.direccioneses = direccioneses;
        this.clientes = clientes;
        this.terceroses = terceroses;
    }

    @Id

    @Column(name = "Id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Id_Tercero_Propietario")
    public Terceros getTerceros() {
        return this.terceros;
    }

    public void setTerceros(Terceros terceros) {
        this.terceros = terceros;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Id_Tipo_Identificacion", nullable = false)
    public TiposIdentificacion getTiposIdentificacion() {
        return this.tiposIdentificacion;
    }

    public void setTiposIdentificacion(TiposIdentificacion tiposIdentificacion) {
        this.tiposIdentificacion = tiposIdentificacion;
    }

    @Column(name = "Numero_Identificacion", nullable = false, length = 20)
    public String getNumeroIdentificacion() {
        return this.numeroIdentificacion;
    }

    public void setNumeroIdentificacion(String numeroIdentificacion) {
        this.numeroIdentificacion = numeroIdentificacion;
    }

    @Column(name = "Digito_Verificacion", nullable = false, length = 1)
    public String getDigitoVerificacion() {
        return this.digitoVerificacion;
    }

    public void setDigitoVerificacion(String digitoVerificacion) {
        this.digitoVerificacion = digitoVerificacion;
    }

    @Column(name = "Codigo", nullable = false, length = 20)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Column(name = "Razon_Social", nullable = false, length = 200)
    public String getRazonSocial() {
        return this.razonSocial;
    }

    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    @Column(name = "Nombres", nullable = false, length = 100)
    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    @Column(name = "Apellidos", nullable = false, length = 100)
    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    @Column(name = "Activo", nullable = false)
    public Boolean getActivo() {
        return this.activo;
    }

    public void setActivo(Boolean activo) {
        this.activo = activo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    @Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
    public String getUsuarioActualizacion() {
        return this.usuarioActualizacion;
    }

    public void setUsuarioActualizacion(String usuarioActualizacion) {
        this.usuarioActualizacion = usuarioActualizacion;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "terceros")
    public OperadoresCentrosDistribucion getOperadoresCentrosDistribucion() {
        return this.operadoresCentrosDistribucion;
    }

    public void setOperadoresCentrosDistribucion(OperadoresCentrosDistribucion operadoresCentrosDistribucion) {
        this.operadoresCentrosDistribucion = operadoresCentrosDistribucion;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "terceros")
    public Destinatarios getDestinatarios() {
        return this.destinatarios;
    }

    public void setDestinatarios(Destinatarios destinatarios) {
        this.destinatarios = destinatarios;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "terceros")
    public Set<Direcciones> getDireccioneses() {
        return this.direccioneses;
    }

    public void setDireccioneses(Set<Direcciones> direccioneses) {
        this.direccioneses = direccioneses;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "terceros")
    public Clientes getClientes() {
        return this.clientes;
    }

    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "terceros")
    public Set<Terceros> getTerceroses() {
        return this.terceroses;
    }

    public void setTerceroses(Set<Terceros> terceroses) {
        this.terceroses = terceroses;
    }

    @Override
    public String toString() {
        return !this.getRazonSocial().isEmpty() && this.getRazonSocial() != null
                ? this.getRazonSocial() : this.nombres + " " + this.apellidos;
    }

}
