package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TiposHorarioPuntoEntrega generated by hbm2java
 */
@Entity
@Table(name = "Tipos_Horario_Punto_Entrega", schema = "tms", catalog = "Tactic", uniqueConstraints = @UniqueConstraint(columnNames = {
		"Id_Cliente", "Codigo" }) )
public class TiposHorarioPuntoEntrega implements java.io.Serializable {

	private Integer id;
	private Clientes clientes;
	private String codigo;
	private String nombre;
	private String descripcion;
	private Integer ordinal;
	private Boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;
	private Set<PedidosDestinosVentanasEntrega> pedidosDestinosVentanasEntregas = new HashSet<PedidosDestinosVentanasEntrega>(
			0);
	private Set<PuntosEntregaHorarios> puntosEntregaHorarioses = new HashSet<PuntosEntregaHorarios>(0);

	public TiposHorarioPuntoEntrega() {
	}

	public TiposHorarioPuntoEntrega(Integer id, Clientes clientes, String codigo, String nombre, String descripcion,
			Integer ordinal, Boolean activo, Date fechaActualizacion, String usuarioActualizacion) {
		this.id = id;
		this.clientes = clientes;
		this.codigo = codigo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.ordinal = ordinal;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	public TiposHorarioPuntoEntrega(Integer id, Clientes clientes, String codigo, String nombre, String descripcion,
			Integer ordinal, Boolean activo, Date fechaActualizacion, String usuarioActualizacion,
			Set<PedidosDestinosVentanasEntrega> pedidosDestinosVentanasEntregas,
			Set<PuntosEntregaHorarios> puntosEntregaHorarioses) {
		this.id = id;
		this.clientes = clientes;
		this.codigo = codigo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.ordinal = ordinal;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
		this.pedidosDestinosVentanasEntregas = pedidosDestinosVentanasEntregas;
		this.puntosEntregaHorarioses = puntosEntregaHorarioses;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Cliente", nullable = false)
	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	@Column(name = "Codigo", nullable = false, length = 20)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "Nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Descripcion", nullable = false, length = 200)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "Ordinal", nullable = false)
	public Integer getOrdinal() {
		return this.ordinal;
	}

	public void setOrdinal(Integer ordinal) {
		this.ordinal = ordinal;
	}

	@Column(name = "Activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tiposHorarioPuntoEntrega")
	public Set<PedidosDestinosVentanasEntrega> getPedidosDestinosVentanasEntregas() {
		return this.pedidosDestinosVentanasEntregas;
	}

	public void setPedidosDestinosVentanasEntregas(
			Set<PedidosDestinosVentanasEntrega> pedidosDestinosVentanasEntregas) {
		this.pedidosDestinosVentanasEntregas = pedidosDestinosVentanasEntregas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tiposHorarioPuntoEntrega")
	public Set<PuntosEntregaHorarios> getPuntosEntregaHorarioses() {
		return this.puntosEntregaHorarioses;
	}

	public void setPuntosEntregaHorarioses(Set<PuntosEntregaHorarios> puntosEntregaHorarioses) {
		this.puntosEntregaHorarioses = puntosEntregaHorarioses;
	}

}
