package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TiposVias generated by hbm2java
 */
@Entity
@Table(name = "Tipos_Vias", schema = "geo", catalog = "Tactic")
public class TiposVias implements java.io.Serializable {

	private TiposViasId id;

	public TiposVias() {
	}

	public TiposVias(TiposViasId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false) ),
			@AttributeOverride(name = "codigo", column = @Column(name = "Codigo", nullable = false, length = 20) ),
			@AttributeOverride(name = "nombre", column = @Column(name = "Nombre", nullable = false, length = 50) ),
			@AttributeOverride(name = "descripcion", column = @Column(name = "Descripcion", nullable = false, length = 200) ),
			@AttributeOverride(name = "ordinal", column = @Column(name = "Ordinal", nullable = false) ),
			@AttributeOverride(name = "activo", column = @Column(name = "Activo", nullable = false) ),
			@AttributeOverride(name = "fechaActualizacion", column = @Column(name = "Fecha_Actualizacion", nullable = false, length = 19) ),
			@AttributeOverride(name = "usuarioActualizacion", column = @Column(name = "Usuario_Actualizacion", nullable = false, length = 50) ) })
	public TiposViasId getId() {
		return this.id;
	}

	public void setId(TiposViasId id) {
		this.id = id;
	}

}
