package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Wh generated by hbm2java
 */
@Entity
@Table(name = "wh", schema = "dbo", catalog = "Tactic")
public class Wh implements java.io.Serializable {

	private WhId id;

	public Wh() {
	}

	public Wh(WhId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "whId", column = @Column(name = "wh_id", nullable = false) ),
			@AttributeOverride(name = "adrId", column = @Column(name = "adr_id", nullable = false) ),
			@AttributeOverride(name = "defWhFlg", column = @Column(name = "def_wh_flg") ),
			@AttributeOverride(name = "whTypCd", column = @Column(name = "wh_typ_cd", nullable = false) ),
			@AttributeOverride(name = "lensSitnam", column = @Column(name = "lens_sitnam") ),
			@AttributeOverride(name = "lensCustomerId", column = @Column(name = "lens_customer_id") ),
			@AttributeOverride(name = "lensCustClientId", column = @Column(name = "lens_cust_client_id") ),
			@AttributeOverride(name = "lensEnaFlg", column = @Column(name = "lens_ena_flg") ),
			@AttributeOverride(name = "dfltHldpfx", column = @Column(name = "dflt_hldpfx") ),
			@AttributeOverride(name = "orgcod", column = @Column(name = "orgcod") ),
			@AttributeOverride(name = "permCreLod", column = @Column(name = "perm_cre_lod") ),
			@AttributeOverride(name = "permAdjLod", column = @Column(name = "perm_adj_lod") ),
			@AttributeOverride(name = "permCreSub", column = @Column(name = "perm_cre_sub") ),
			@AttributeOverride(name = "permAdjSub", column = @Column(name = "perm_adj_sub") ),
			@AttributeOverride(name = "moddte", column = @Column(name = "moddte", length = 23) ),
			@AttributeOverride(name = "modUsrId", column = @Column(name = "mod_usr_id") ),
			@AttributeOverride(name = "sgln", column = @Column(name = "sgln") ),
			@AttributeOverride(name = "rfidEnaFlg", column = @Column(name = "rfid_ena_flg") ),
			@AttributeOverride(name = "transWhId", column = @Column(name = "trans_wh_id") ),
			@AttributeOverride(name = "autoPlayCstThr", column = @Column(name = "auto_play_cst_thr", scale = 4) ),
			@AttributeOverride(name = "cntThrUnit", column = @Column(name = "cnt_thr_unit") ),
			@AttributeOverride(name = "cntThrCst", column = @Column(name = "cnt_thr_cst", scale = 4) ),
			@AttributeOverride(name = "UVersion", column = @Column(name = "u_version") ),
			@AttributeOverride(name = "insDt", column = @Column(name = "ins_dt", length = 23) ),
			@AttributeOverride(name = "lastUpdDt", column = @Column(name = "last_upd_dt", length = 23) ),
			@AttributeOverride(name = "insUserId", column = @Column(name = "ins_user_id") ),
			@AttributeOverride(name = "lastUpdUserId", column = @Column(name = "last_upd_user_id") ),
			@AttributeOverride(name = "aisleMax", column = @Column(name = "aisle_max") ),
			@AttributeOverride(name = "bayMax", column = @Column(name = "bay_max") ),
			@AttributeOverride(name = "slotMax", column = @Column(name = "slot_max") ),
			@AttributeOverride(name = "concatOrder", column = @Column(name = "concat_order") ),
			@AttributeOverride(name = "recalcDistFlag", column = @Column(name = "recalc_dist_flag") ),
			@AttributeOverride(name = "recalcDate", column = @Column(name = "recalc_date", length = 23) ),
			@AttributeOverride(name = "lastRegenTime", column = @Column(name = "last_regen_time") ),
			@AttributeOverride(name = "wmpLeftX", column = @Column(name = "wmp_left_x") ),
			@AttributeOverride(name = "wmpRightX", column = @Column(name = "wmp_right_x") ),
			@AttributeOverride(name = "wmpUpperY", column = @Column(name = "wmp_upper_y") ),
			@AttributeOverride(name = "wmpLowerY", column = @Column(name = "wmp_lower_y") ),
			@AttributeOverride(name = "active", column = @Column(name = "active") ),
			@AttributeOverride(name = "crncyCode", column = @Column(name = "crncy_code") ),
			@AttributeOverride(name = "lstRttnId", column = @Column(name = "lst_rttn_id") ),
			@AttributeOverride(name = "rttnIdMinValue", column = @Column(name = "rttn_id_min_value") ),
			@AttributeOverride(name = "rttnIdMaxValue", column = @Column(name = "rttn_id_max_value") ),
			@AttributeOverride(name = "adjThrCst", column = @Column(name = "adj_thr_cst", scale = 4) ),
			@AttributeOverride(name = "adjThrUnit", column = @Column(name = "adj_thr_unit") ),
			@AttributeOverride(name = "cnsgCod", column = @Column(name = "cnsg_cod") ),
			@AttributeOverride(name = "cnsgPeriod", column = @Column(name = "cnsg_period") ) })
	public WhId getId() {
		return this.id;
	}

	public void setId(WhId id) {
		this.id = id;
	}

}
