package com.tacticlogistics.crm.model.entities;
// Generated 28-nov-2015 7:36:03 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ZonasCoberturaCiudades generated by hbm2java
 */
@Entity
@Table(name = "Zonas_Cobertura_Ciudades", schema = "wms", catalog = "Tactic")
public class ZonasCoberturaCiudades implements java.io.Serializable {

	private Integer id;
	private Integer idZonaCobertura;
	private Integer idCiudad;
	private Boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;

	public ZonasCoberturaCiudades() {
	}

	public ZonasCoberturaCiudades(Integer id, Integer idZonaCobertura, Integer idCiudad, Boolean activo,
			Date fechaActualizacion, String usuarioActualizacion) {
		this.id = id;
		this.idZonaCobertura = idZonaCobertura;
		this.idCiudad = idCiudad;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Id_Zona_Cobertura", nullable = false)
	public Integer getIdZonaCobertura() {
		return this.idZonaCobertura;
	}

	public void setIdZonaCobertura(Integer idZonaCobertura) {
		this.idZonaCobertura = idZonaCobertura;
	}

	@Column(name = "Id_Ciudad", nullable = false)
	public Integer getIdCiudad() {
		return this.idCiudad;
	}

	public void setIdCiudad(Integer idCiudad) {
		this.idCiudad = idCiudad;
	}

	@Column(name = "Activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

}
