package com.tacticlogistics.crm.model.entities.app;
// Generated 19-feb-2016 15:47:47 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

/**
 * Menus generated by hbm2java
 */
@Entity
@Table(name = "Menus", schema = "ui", catalog = "Tactic")
public class Menus implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private Menus menus;
    private String nombre;
    private String icono;
    private String comando;
    private String pagina;
    private Integer ordinal;
    private Set<Menus> menuses = new HashSet<>(0);
    private Set<RolesMenus> rolesMenuses = new HashSet<>(0);

    public Menus() {
    }

    public Menus(Integer id, Integer ordinal) {
        this.id = id;
        this.ordinal = ordinal;
    }

    public Menus(Integer id, Menus menus, String nombre, String icono, String comando, String pagina, Integer ordinal,
            Set<Menus> menuses, Set<RolesMenus> rolesMenuses) {
        this.id = id;
        this.menus = menus;
        this.nombre = nombre;
        this.icono = icono;
        this.comando = comando;
        this.pagina = pagina;
        this.ordinal = ordinal;
        this.menuses = menuses;
        this.rolesMenuses = rolesMenuses;
    }

    @Id
    @Column(name = "Id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Id_Menu_Padre")
    public Menus getMenus() {
        return this.menus;
    }

    public void setMenus(Menus menus) {
        this.menus = menus;
    }

    @Column(name = "Nombre", length = 50)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "Icono", length = 50)
    public String getIcono() {
        return this.icono;
    }

    public void setIcono(String icono) {
        this.icono = icono;
    }

    @Column(name = "Comando", length = 200)
    public String getComando() {
        return this.comando;
    }

    public void setComando(String comando) {
        this.comando = comando;
    }

    @Column(name = "Pagina", length = 200)
    public String getPagina() {
        return this.pagina;
    }

    public void setPagina(String pagina) {
        this.pagina = pagina;
    }

    @Column(name = "ordinal", nullable = false)
    //@OrderBy(value = "ordinal")
    public Integer getOrdinal() {
        return this.ordinal;
    }

    public void setOrdinal(Integer ordinal) {
        this.ordinal = ordinal;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "menus")
    public Set<Menus> getMenuses() {
        return this.menuses;
    }

    public void setMenuses(Set<Menus> menuses) {
        this.menuses = menuses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "menus")
    public Set<RolesMenus> getRolesMenuses() {
        return this.rolesMenuses;
    }

    public void setRolesMenuses(Set<RolesMenus> rolesMenuses) {
        this.rolesMenuses = rolesMenuses;
    }

}
