package com.tacticlogistics.crm.model.entities.app;
// Generated 19-feb-2016 15:47:47 by Hibernate Tools 4.3.1.Final

import com.tacticlogistics.crm.model.entities.EntityId;
import java.util.Date;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "Roles", schema = "app", catalog = "Tactic")
public class Roles implements java.io.Serializable, EntityId {

    private static final long serialVersionUID = 1L;
    private Integer id;
    private String rol;
    private Boolean activo;
    private Date fechaActualizacion;
    private String usuarioActualizacion;
    private List<RolesMenus> rolesMenuses = new LinkedList<>();
    private Set<UsuariosRoles> usuariosRoleses = new HashSet<>(0);

    public Roles() {
    }

    public Roles(Integer id, String rol, Boolean activo, Date fechaActualizacion, String usuarioActualizacion) {
        this.id = id;
        this.rol = rol;
        this.activo = activo;
        this.fechaActualizacion = fechaActualizacion;
        this.usuarioActualizacion = usuarioActualizacion;
    }

    public Roles(Integer id, String rol, Boolean activo, Date fechaActualizacion, String usuarioActualizacion,
            List<RolesMenus> rolesMenuses, Set<UsuariosRoles> usuariosRoleses) {
        this.id = id;
        this.rol = rol;
        this.activo = activo;
        this.fechaActualizacion = fechaActualizacion;
        this.usuarioActualizacion = usuarioActualizacion;
        this.rolesMenuses = rolesMenuses;
        this.usuariosRoleses = usuariosRoleses;
    }

    @Id
    @GeneratedValue(strategy = javax.persistence.GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "Rol", nullable = false, length = 100)
    public String getRol() {
        return this.rol;
    }

    public void setRol(String rol) {
        this.rol = rol;
    }

    @Column(name = "Activo", nullable = false)
    public Boolean getActivo() {
        return this.activo;
    }

    public void setActivo(Boolean activo) {
        this.activo = activo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    @Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
    public String getUsuarioActualizacion() {
        return this.usuarioActualizacion;
    }

    public void setUsuarioActualizacion(String usuarioActualizacion) {
        this.usuarioActualizacion = usuarioActualizacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "roles", cascade = CascadeType.ALL)
    public List<RolesMenus> getRolesMenuses() {
        return this.rolesMenuses;
    }

    public void setRolesMenuses(List<RolesMenus> rolesMenuses) {
        this.rolesMenuses = rolesMenuses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
    public Set<UsuariosRoles> getUsuariosRoleses() {
        return this.usuariosRoleses;
    }

    public void setUsuariosRoleses(Set<UsuariosRoles> usuariosRoleses) {
        this.usuariosRoleses = usuariosRoleses;
    }

}
