package com.tacticlogistics.crm.model.entities.app;
// Generated 19-feb-2016 15:47:47 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.OrderBy;

/**
 * RolesMenus generated by hbm2java
 */
@Entity
@Table(name = "Roles_Menus", schema = "app", catalog = "Tactic")
public class RolesMenus implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    private Integer id;
    private Roles roles;
    private Menus menus;

    public RolesMenus() {
    }

    public RolesMenus(Integer id, Roles roles, Menus menus) {
        this.id = id;
        this.roles = roles;
        this.menus = menus;
    }

    @Id
    @GeneratedValue(strategy = javax.persistence.GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Id_Roles", nullable = false)
    public Roles getRoles() {
        return this.roles;
    }

    public void setRoles(Roles roles) {
        this.roles = roles;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "Id_Menus", nullable = false)
    @OrderBy(clause = "ordinal")
    public Menus getMenus() {
        return this.menus;
    }

    public void setMenus(Menus menus) {
        this.menus = menus;
    }

}
