package com.tacticlogistics.crm.model.entities.app;
// Generated 19-feb-2016 15:47:47 by Hibernate Tools 4.3.1.Final

import com.tacticlogistics.crm.model.entities.EntityId;
import java.util.Date;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "Usuarios", schema = "app", catalog = "Tactic")
public class Usuarios implements java.io.Serializable, EntityId {

    private static final long serialVersionUID = 1L;
    private Integer id;
    private String usuario;
    private String nombres;
    private String apellidos;
    private String email;
    private Boolean activo;
    private Date fechaActualizacion;
    private String usuarioActualizacion;
    private String clave;
    private List<UsuariosRoles> usuariosRoleses = new LinkedList<>();

    public Usuarios() {
    }

    public Usuarios(Integer id, String usuario, String nombres, String apellidos, Boolean activo,
            Date fechaActualizacion, String usuarioActualizacion) {
        this.id = id;
        this.usuario = usuario;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.activo = activo;
        this.fechaActualizacion = fechaActualizacion;
        this.usuarioActualizacion = usuarioActualizacion;
    }

    public Usuarios(Integer id, String usuario, String nombres, String apellidos, String email, Boolean activo,
            Date fechaActualizacion, String usuarioActualizacion, String clave, List<UsuariosRoles> usuariosRoleses) {
        this.id = id;
        this.usuario = usuario;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.email = email;
        this.activo = activo;
        this.fechaActualizacion = fechaActualizacion;
        this.usuarioActualizacion = usuarioActualizacion;
        this.clave = clave;
        this.usuariosRoleses = usuariosRoleses;
    }

    @Id
    @GeneratedValue(strategy = javax.persistence.GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "Usuario", nullable = false, length = 100)
    public String getUsuario() {
        return this.usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    @Column(name = "Nombres", nullable = false, length = 100)
    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    @Column(name = "Apellidos", nullable = false, length = 100)
    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    @Column(name = "Email", nullable = false, length = 200)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "Activo", nullable = false)
    public Boolean getActivo() {
        return this.activo;
    }

    public void setActivo(Boolean activo) {
        this.activo = activo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    @Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
    public String getUsuarioActualizacion() {
        return this.usuarioActualizacion;
    }

    public void setUsuarioActualizacion(String usuarioActualizacion) {
        this.usuarioActualizacion = usuarioActualizacion;
    }

    @Column(name = "clave", nullable = false, length = 50)
    public String getClave() {
        return this.clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarios", cascade = CascadeType.ALL)
    public List<UsuariosRoles> getUsuariosRoleses() {
        return this.usuariosRoleses;
    }

    public void setUsuariosRoleses(List<UsuariosRoles> usuariosRoleses) {
        this.usuariosRoleses = usuariosRoleses;
    }

}
