package com.tacticlogistics.crm.model.entities.dashboard;
// Generated 29-oct-2015 10:32:55 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mediciones generated by hbm2java
 */
@Entity
@Table(name = "Mediciones", catalog = "dashboard")
public class Mediciones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Indicadores indicadores;
	private UoMDB uoM;
	private UoT uoT;
	private Integer idCliente;
	private String periodo;
	private BigDecimal valorMedicion;
	private BigDecimal valorMeta;
	private Boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;

	public Mediciones() {
	}

	public Mediciones(Integer id, Indicadores indicadores, UoMDB uoM, UoT uoT, Integer idCliente, String periodo,
			BigDecimal valorMedicion, BigDecimal valorMeta, Boolean activo, Date fechaActualizacion,
			String usuarioActualizacion) {
		this.id = id;
		this.indicadores = indicadores;
		this.uoM = uoM;
		this.uoT = uoT;
		this.idCliente = idCliente;
		this.periodo = periodo;
		this.valorMedicion = valorMedicion;
		this.valorMeta = valorMeta;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Indicador", nullable = false)
	public Indicadores getIndicadores() {
		return this.indicadores;
	}

	public void setIndicadores(Indicadores indicadores) {
		this.indicadores = indicadores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_UoM", nullable = false)
	public UoMDB getUoM() {
		return this.uoM;
	}

	public void setUoM(UoMDB uoM) {
		this.uoM = uoM;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_UoT", nullable = false)
	public UoT getUoT() {
		return this.uoT;
	}

	public void setUoT(UoT uoT) {
		this.uoT = uoT;
	}

	@Column(name = "Id_Cliente", nullable = false)
	public Integer getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(Integer idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "Periodo", nullable = false, length = 20)
	public String getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(String periodo) {
		this.periodo = periodo;
	}

	@Column(name = "Valor_Medicion", nullable = false, precision = 14, scale = 4)
	public BigDecimal getValorMedicion() {
		return this.valorMedicion;
	}

	public void setValorMedicion(BigDecimal valorMedicion) {
		this.valorMedicion = valorMedicion;
	}

	@Column(name = "Valor_Meta", nullable = false, precision = 14, scale = 4)
	public BigDecimal getValorMeta() {
		return this.valorMeta;
	}

	public void setValorMeta(BigDecimal valorMeta) {
		this.valorMeta = valorMeta;
	}

	@Column(name = "Activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

}
