package com.tacticlogistics.crm.model.entities.dashboard;
// Generated 29-oct-2015 10:32:55 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Metas generated by hbm2java
 */
@Entity
@Table(name = "Metas", catalog = "dashboard")
public class Metas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Indicadores indicadores;
	private BigDecimal valorMeta;
	private Date fechaDesde;
	private Date fechaHasta;
	private Boolean activo;
	private Date fechaActualizacion;
	private String usuarioActualizacion;

	public Metas() {
	}

	public Metas(Integer id, Indicadores indicadores, BigDecimal valorMeta, Date fechaDesde, Date fechaHasta,
			Boolean activo, Date fechaActualizacion, String usuarioActualizacion) {
		this.id = id;
		this.indicadores = indicadores;
		this.valorMeta = valorMeta;
		this.fechaDesde = fechaDesde;
		this.fechaHasta = fechaHasta;
		this.activo = activo;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Id_Indicador", nullable = false)
	public Indicadores getIndicadores() {
		return this.indicadores;
	}

	public void setIndicadores(Indicadores indicadores) {
		this.indicadores = indicadores;
	}

	@Column(name = "Valor_Meta", nullable = false, precision = 14, scale = 4)
	public BigDecimal getValorMeta() {
		return this.valorMeta;
	}

	public void setValorMeta(BigDecimal valorMeta) {
		this.valorMeta = valorMeta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Desde", nullable = false, length = 19)
	public Date getFechaDesde() {
		return this.fechaDesde;
	}

	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Hasta", nullable = false, length = 19)
	public Date getFechaHasta() {
		return this.fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}

	@Column(name = "Activo", nullable = false)
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

}
