package com.tacticlogistics.crm.model.entities.dashboard;
// Generated 30-oct-2015 11:50:47 by Hibernate Tools 4.3.1.Final

import com.tacticlogistics.crm.model.entities.EntityId;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Resultados generated by hbm2java
 */
@Entity
@Table(name = "resultados", catalog = "dashboard")
public class Resultados implements java.io.Serializable, EntityId {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Integer annio;
	private Integer mes;
	private String kpi;
	private String unidad;
	private BigDecimal real;
	private BigDecimal planeado;

	public Resultados() {
	}

	public Resultados(Integer id) {
		this.id = id;
	}

	public Resultados(Integer id, Integer annio, Integer mes, String kpi, String unidad, BigDecimal real,
			BigDecimal plan) {
		this.id = id;
		this.annio = annio;
		this.mes = mes;
		this.kpi = kpi;
		this.unidad = unidad;
		this.real = real;
		this.planeado = plan;
	}

	@Override
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	@Override
	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "annio")
	public Integer getAnnio() {
		return this.annio;
	}

	public void setAnnio(Integer annio) {
		this.annio = annio;
	}

	@Column(name = "mes")
	public Integer getMes() {
		return this.mes;
	}

	public void setMes(Integer mes) {
		this.mes = mes;
	}

	@Column(name = "kpi", length = 50)
	public String getKpi() {
		return this.kpi;
	}

	public void setKpi(String kpi) {
		this.kpi = kpi;
	}

	@Column(name = "Unidad", length = 50)
	public String getUnidad() {
		return this.unidad;
	}

	public void setUnidad(String unidad) {
		this.unidad = unidad;
	}

	@Column(name = "Real", precision = 38, scale = 10)
	public BigDecimal getReal() {
		return this.real;
	}

	public void setReal(BigDecimal real) {
		this.real = real;
	}

	@Column(name = "planeado", precision = 38, scale = 10)
	public BigDecimal getPlaneado() {
		return this.planeado;
	}

	public void setPlaneado(BigDecimal planeado) {
		this.planeado = planeado;
	}

}
