package com.tacticlogistics.crm.model.entities.radicacion;
// Generated 05-feb-2016 6:28:15 by Hibernate Tools 4.3.1.Final

import com.tacticlogistics.crm.model.entities.EntityId;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ArchivosRadicados generated by hbm2java
 */
@Entity
@Table(name = "Archivos_Radicados", schema = "radicacion", catalog = "Tactic")
public class ArchivosRadicados implements java.io.Serializable, EntityId {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private Integer idCliente;
    private Integer idTipoArchivoRadicado;
    private Integer idEstadoArchivoRadicado;
    private String nombreArchivo;
    private Integer numeroRegistrosCargados;
    private Integer numeroEntidadesCargadas;
    private String codigoHash;
    private Date fechaRadicacion;
    private String usuarioRadicacion;
    private Date fechaDeAlta;
    private Date fechaDeBaja;
    private Date fechaActualizacion;
    private String usuarioActualizacion;

    public ArchivosRadicados() {
    }

    public ArchivosRadicados(Integer id, Integer idCliente, Integer idTipoArchivoRadicado,
            Integer idEstadoArchivoRadicado, String nombreArchivo, Integer numeroRegistrosCargados,
            Integer numeroEntidadesCargadas, String codigoHash, Date fechaRadicacion, String usuarioRadicacion,
            Date fechaDeAlta, Date fechaDeBaja, Date fechaActualizacion, String usuarioActualizacion) {
        this.id = id;
        this.idCliente = idCliente;
        this.idTipoArchivoRadicado = idTipoArchivoRadicado;
        this.idEstadoArchivoRadicado = idEstadoArchivoRadicado;
        this.nombreArchivo = nombreArchivo;
        this.numeroRegistrosCargados = numeroRegistrosCargados;
        this.numeroEntidadesCargadas = numeroEntidadesCargadas;
        this.codigoHash = codigoHash;
        this.fechaRadicacion = fechaRadicacion;
        this.usuarioRadicacion = usuarioRadicacion;
        this.fechaDeAlta = fechaDeAlta;
        this.fechaDeBaja = fechaDeBaja;
        this.fechaActualizacion = fechaActualizacion;
        this.usuarioActualizacion = usuarioActualizacion;
    }

    @Id
    @GeneratedValue(strategy = javax.persistence.GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "Id_Cliente", nullable = true)
    public Integer getIdCliente() {
        return this.idCliente;
    }

    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    @Column(name = "Id_Tipo_Archivo_Radicado", nullable = false)
    public Integer getIdTipoArchivoRadicado() {
        return this.idTipoArchivoRadicado;
    }

    public void setIdTipoArchivoRadicado(Integer idTipoArchivoRadicado) {
        this.idTipoArchivoRadicado = idTipoArchivoRadicado;
    }

    @Column(name = "ID_Estado_Archivo_Radicado", nullable = false)
    public Integer getIdEstadoArchivoRadicado() {
        return this.idEstadoArchivoRadicado;
    }

    public void setIdEstadoArchivoRadicado(Integer idEstadoArchivoRadicado) {
        this.idEstadoArchivoRadicado = idEstadoArchivoRadicado;
    }

    @Column(name = "Nombre_Archivo", nullable = false, length = 100)
    public String getNombreArchivo() {
        return this.nombreArchivo;
    }

    public void setNombreArchivo(String nombreArchivo) {
        this.nombreArchivo = nombreArchivo;
    }

    @Column(name = "Numero_Registros_Cargados", nullable = false)
    public Integer getNumeroRegistrosCargados() {
        return this.numeroRegistrosCargados;
    }

    public void setNumeroRegistrosCargados(Integer numeroRegistrosCargados) {
        this.numeroRegistrosCargados = numeroRegistrosCargados;
    }

    @Column(name = "Numero_Entidades_Cargadas", nullable = false)
    public Integer getNumeroEntidadesCargadas() {
        return this.numeroEntidadesCargadas;
    }

    public void setNumeroEntidadesCargadas(Integer numeroEntidadesCargadas) {
        this.numeroEntidadesCargadas = numeroEntidadesCargadas;
    }

    @Column(name = "Codigo_Hash", nullable = true, length = 100)
    public String getCodigoHash() {
        return this.codigoHash;
    }

    public void setCodigoHash(String codigoHash) {
        this.codigoHash = codigoHash;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Fecha_Radicacion", nullable = false, length = 19)
    public Date getFechaRadicacion() {
        return this.fechaRadicacion;
    }

    public void setFechaRadicacion(Date fechaRadicacion) {
        this.fechaRadicacion = fechaRadicacion;
    }

    @Column(name = "Usuario_Radicacion", nullable = false, length = 50)
    public String getUsuarioRadicacion() {
        return this.usuarioRadicacion;
    }

    public void setUsuarioRadicacion(String usuarioRadicacion) {
        this.usuarioRadicacion = usuarioRadicacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Fecha_De_Alta", nullable = true, length = 19)
    public Date getFechaDeAlta() {
        return this.fechaDeAlta;
    }

    public void setFechaDeAlta(Date fechaDeAlta) {
        this.fechaDeAlta = fechaDeAlta;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Fecha_De_Baja", nullable = true, length = 19)
    public Date getFechaDeBaja() {
        return this.fechaDeBaja;
    }

    public void setFechaDeBaja(Date fechaDeBaja) {
        this.fechaDeBaja = fechaDeBaja;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "Fecha_Actualizacion", nullable = true, length = 19)
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    @Column(name = "Usuario_Actualizacion", nullable = true, length = 50)
    public String getUsuarioActualizacion() {
        return this.usuarioActualizacion;
    }

    public void setUsuarioActualizacion(String usuarioActualizacion) {
        this.usuarioActualizacion = usuarioActualizacion;
    }

}
