package com.tacticlogistics.crm.model.entities.radicacion;
// Generated 05-feb-2016 6:28:15 by Hibernate Tools 4.3.1.Final

import com.tacticlogistics.crm.model.entities.EntityId;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrdenesVentasSecundariaLog generated by hbm2java
 */
@Entity
@Table(name = "Ordenes_Ventas_Secundaria_Log", schema = "radicacion", catalog = "Tactic")
public class OrdenesVentasSecundariaLog implements java.io.Serializable, EntityId {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private Integer id;
    private Integer idArchivoRadicado;
    private Integer idOrdenVentaSecundaria;
    private String codigoTipoMensaje;
    private String codigoMensaje;
    private String mensaje;

    public OrdenesVentasSecundariaLog() {
    }

    public OrdenesVentasSecundariaLog(Integer id, Integer idArchivoRadicado, Integer idOrdenVentaSecundaria,
            String codigoTipoMensaje, String codigoMensaje, String mensaje) {
        this.id = id;
        this.idArchivoRadicado = idArchivoRadicado;
        this.idOrdenVentaSecundaria = idOrdenVentaSecundaria;
        this.codigoTipoMensaje = codigoTipoMensaje;
        this.codigoMensaje = codigoMensaje;
        this.mensaje = mensaje;
    }

    @Id
    @GeneratedValue(strategy = javax.persistence.GenerationType.IDENTITY)
    @Column(name = "Id", unique = true, nullable = false)
    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "Id_Archivo_Radicado", nullable = false)
    public Integer getIdArchivoRadicado() {
        return this.idArchivoRadicado;
    }

    public void setIdArchivoRadicado(Integer idArchivoRadicado) {
        this.idArchivoRadicado = idArchivoRadicado;
    }

    @Column(name = "Id_Orden_Venta_Secundaria", nullable = false)
    public Integer getIdOrdenVentaSecundaria() {
        return this.idOrdenVentaSecundaria;
    }

    public void setIdOrdenVentaSecundaria(Integer idOrdenVentaSecundaria) {
        this.idOrdenVentaSecundaria = idOrdenVentaSecundaria;
    }

    @Column(name = "Codigo_Tipo_Mensaje", nullable = false, length = 1)
    public String getCodigoTipoMensaje() {
        return this.codigoTipoMensaje;
    }

    public void setCodigoTipoMensaje(String codigoTipoMensaje) {
        this.codigoTipoMensaje = codigoTipoMensaje;
    }

    @Column(name = "Codigo_Mensaje", nullable = false, length = 20)
    public String getCodigoMensaje() {
        return this.codigoMensaje;
    }

    public void setCodigoMensaje(String codigoMensaje) {
        this.codigoMensaje = codigoMensaje;
    }

    @Column(name = "Mensaje", nullable = false, length = 1000)
    public String getMensaje() {
        return this.mensaje;
    }

    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }

}
