package com.tacticlogistics.crm.model.entities.radicacion;
// Generated 05-feb-2016 6:28:15 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TiposCampo generated by hbm2java
 */
@Entity
@Table(name = "Tipos_Campo", schema = "radicacion", catalog = "Tactic")
public class TiposCampo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String dataType;
	private Integer id;
	private Boolean usaLongitud;
	private Boolean usaPrecisionNumerica;
	private Boolean usaEscalaNumerica;
	private Date fechaActualizacion;
	private String usuarioActualizacion;

	public TiposCampo() {
	}

	public TiposCampo(String dataType, Integer id, Boolean usaLongitud, Boolean usaPrecisionNumerica,
			Boolean usaEscalaNumerica, Date fechaActualizacion, String usuarioActualizacion) {
		this.dataType = dataType;
		this.id = id;
		this.usaLongitud = usaLongitud;
		this.usaPrecisionNumerica = usaPrecisionNumerica;
		this.usaEscalaNumerica = usaEscalaNumerica;
		this.fechaActualizacion = fechaActualizacion;
		this.usuarioActualizacion = usuarioActualizacion;
	}

	@Id

	@Column(name = "DATA_TYPE", unique = true, nullable = false, length = 256)
	public String getDataType() {
		return this.dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	@Column(name = "Id", nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Usa_Longitud", nullable = false)
	public Boolean getUsaLongitud() {
		return this.usaLongitud;
	}

	public void setUsaLongitud(Boolean usaLongitud) {
		this.usaLongitud = usaLongitud;
	}

	@Column(name = "Usa_Precision_Numerica", nullable = false)
	public Boolean getUsaPrecisionNumerica() {
		return this.usaPrecisionNumerica;
	}

	public void setUsaPrecisionNumerica(Boolean usaPrecisionNumerica) {
		this.usaPrecisionNumerica = usaPrecisionNumerica;
	}

	@Column(name = "Usa_Escala_Numerica", nullable = false)
	public Boolean getUsaEscalaNumerica() {
		return this.usaEscalaNumerica;
	}

	public void setUsaEscalaNumerica(Boolean usaEscalaNumerica) {
		this.usaEscalaNumerica = usaEscalaNumerica;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha_Actualizacion", nullable = false, length = 19)
	public Date getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(Date fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	@Column(name = "Usuario_Actualizacion", nullable = false, length = 50)
	public String getUsuarioActualizacion() {
		return this.usuarioActualizacion;
	}

	public void setUsuarioActualizacion(String usuarioActualizacion) {
		this.usuarioActualizacion = usuarioActualizacion;
	}

}
